### ISSUE TITLE
Rufus stopping after about 6 minutes

### ISSUE THREAD

**Issue by PlatformIntegrity** [jmettraux/rufus-scheduler#139]
Hey guys, I am currently using rufus-scheduler gem with my rails-app which is being redeployed every hour using chef and managed by nginx in conjunction with passenger. I had a couple of jobs that ran once a day, when the run time is within a couple of minutes of chef finishing and restarting nginx service it seems to run fine, outside of that windows the scheduler does not run at all. In light of that, I added a job that simply puts out to the logger every 2 minutes. The new job only prints out 3 times the puts statement then quits with no apparent reasons... Any idea what could be happening here?
TD;LR: Rufus seems to run within 6 minutes after restarting nginx and dies from then on...Please help

**Comment by jmettraux** [comment]
Details please. http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by jmettraux** [comment]
Passenger...

Please read the FAQ: https://github.com/jmettraux/rufus-scheduler#faq
This can help as well: http://stackoverflow.com/questions/tagged/rufus-scheduler+passenger

Closing as it's the classical "Passenger kills my rufus-scheduler thread".
