### ISSUE TITLE
wrong behaviour on some cron syntaxes

### ISSUE THREAD

**Issue by ketan** [jmettraux/rufus-scheduler#144]
The cron expression `23 10/2 * * *` means *every 23rd minute past the 10, 12, 14, 16, 18, 20 and 22nd hour*

rufus-scheduler is not in a position to understand, parse or execute stuff in accordance with this specification -

```ruby
s = Rufus::Scheduler::CronLine.new('23 10/2 * * *')
t0 = Time.at(0) #unix epoch
10.times {
  puts "Next time - #{t0 = s.next_time(t0)}"
}
```

Generated output - 

```
Next time - 1970-01-01 10:23:00 +0000
Next time - 1970-01-02 10:23:00 +0000
Next time - 1970-01-03 10:23:00 +0000
Next time - 1970-01-04 10:23:00 +0000
Next time - 1970-01-05 10:23:00 +0000
Next time - 1970-01-06 10:23:00 +0000
Next time - 1970-01-07 10:23:00 +0000
Next time - 1970-01-08 10:23:00 +0000
Next time - 1970-01-09 10:23:00 +0000
Next time - 1970-01-10 10:23:00 +0000
```

Expected output is -

```
Next time - 1970-01-01 10:23:00 +0000
Next time - 1970-01-01 12:23:00 +0000
Next time - 1970-01-01 14:23:00 +0000
Next time - 1970-01-01 16:23:00 +0000
Next time - 1970-01-01 18:23:00 +0000
Next time - 1970-01-01 22:23:00 +0000
Next time - 1970-01-02 10:23:00 +0000
```

**Comment by jmettraux** [comment]
Thanks! I'll fix that.

**Comment by jmettraux** [comment]
Fixed title, since rufus-scheduler obviously parses the cron syntax.

**Comment by jmettraux** [comment]
`man 5 crontab`

> Step values can be used in conjunction with ranges.  Following a	 range
       with  "<number>"	 specifies  skips  of  the  number's value through the
       range.  For example, "0-23/2" can be used in the hours field to specify
       command	execution every other hour (the alternative in the V7 standard
       is "0,2,4,6,8,10,12,14,16,18,20,22").  Steps are also  permitted	 after
       an asterisk, so if you want to say "every two hours", just use "*/2".

Rufus-scheduler behaves correctly.

Please use `23 10-23/2 * * *`

**Comment by ketan** [comment]
Sorry about that. You are right, I tried typing the invalid cron using `crontab -e` and it was not accepted.

**Comment by jmettraux** [comment]
OK, my Debian GNU/Linux's `crontab -e` doesn't complain on `23 10/2 * * *`. IMHO, it's valid, the range is simply 10 to 10.

**Comment by ketan** [comment]
I did this on my centos and `crontab -e` asked me if I wanted to rectify an invalid cron. Some details and differences between centos/ubuntu follow -

### Centos

```
$ cat /etc/centos-release
CentOS release 6.6 (Final)

$ rpm -qf $(which crontab)
cronie-1.4.4-12.el6.x86_64

$ echo '35/3 * * * * date >> /tmp/cron-execution' > my-crontab

$ sudo crontab -u vagrant my-crontab
"foo":1: bad minute
errors in crontab file, can't install.
```

### Ubuntu 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

$ dpkg -S $(which crontab)
cron: /usr/bin/crontab

$ apt-cache show cron | grep -i version
Version: 3.0pl1-124ubuntu2

$ echo '35/3 * * * * date >> /tmp/cron-execution' > my-crontab
```

In some time, I'll report on the contents of the /tmp/cron-execution to report the behaviour of the cron syntax.

**Comment by ketan** [comment]
Here goes, quite unexpected from what I was thinking about.

```
$ tail -f /tmp/cron-execution
Fri Mar 27 03:35:01 UTC 2015
Fri Mar 27 04:35:01 UTC 2015
```

**Comment by jmettraux** [comment]
> The cron expression 23 10/2 * * * means every 23rd minute past the 10, 12, 14, 16, 18, 20 and 22nd hour
>
> rufus-scheduler is not in a position to understand, parse or execute stuff in accordance with this specification

If we were to follow your specification, then "23 10 * * *" could mean "every 23rd minute past the 10, 11, 12, ..., 23rd hour".

;-)

**Comment by ketan** [comment]
I'm sorry about that. I should have read and understood the manual better.

**Comment by jmettraux** [comment]
Hey, no worries. Thanks for your help.
