### ISSUE TITLE
Cron job ignores :first_at

### ISSUE THREAD

**Issue by mguymon** [jmettraux/rufus-scheduler#148]
When using cron to schedule a job, `:first_at` of a DateTime has no effect on the `next_time`. 

    the_fuuuuture = DateTime.parse('2020-01-01 15:00')
    Rufus::Scheduler.singleton.cron('45 15 * * *', first_at: the_fuuuuture, job: true).next_time

The result of `next_time` will be the next immediate schedule, e.g. today at 15:45, instead of all the way into the fuuuuture in the year 2020.

Rufus version 3.0.9

**Comment by jmettraux** [comment]
Thanks.
