### ISSUE TITLE
Scheduler caught exception

### ISSUE THREAD

**Issue by howardsternisbatman** [jmettraux/rufus-scheduler#150]
hello,

I have a Dashing dashboard using the spreadsheet gem, everything works correctly but after about 30 minutes Scheduler throws a fit in the console window.

Any ideas?

thanks.

scheduler caught exception:scheduler caught exception:
scheduler caught exception:scheduler caught exception:

================================================================================scheduler caught exception:
scheduler caught exception:
Too many open files - /tmp/oo_20150330-8033-9yqvkx/.

scheduler caught exception:
scheduler caught exception:
/var/lib/gems/1.9.1/gems/spreadsheet-1.0.1/lib/spreadsheet.rb:71:in `initialize'

Too many open files - /home/administrator/manchvegas/xls/newcases.xls

**Comment by jmettraux** [comment]
Hello,

it says "Too many open files - /home/administrator/manchvegas/xls/newcases.xls".

Your code seems to open files and not close them. Fix this by closing the files.

Closing the issue since it is not a rufus-scheduler issue.

Kind regards.
