### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by dentarg** [jmettraux/rufus-scheduler#156]
This an obscure error I've encountered in a project using rufus-scheduler. I have not tried to reproduce the bug, as I've only seen it a total of two times during ~1 year. Just wanted to check if you would be able to understand the issue from the information I have available. If not, feel free to close this issue.

```
Stacktrace (most recent call first):

  NoMethodError: undefined method `+' for nil:NilClass   ### reminder (added by jmettraux)

  rufus/scheduler.rb:600:in `block in timeout_jobs'
    to = to.is_a?(Time) ? to : ts + to
  rufus/scheduler.rb:591:in `each'
    work_threads(:active).each do |t|
  rufus/scheduler.rb:591:in `timeout_jobs'
    work_threads(:active).each do |t|
  rufus/scheduler.rb:563:in `block in start'
    timeout_jobs
  logging/diagnostic_context.rb:323:in `call'
    b.call(*args)
  logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
    b.call(*args)
```

I gather it is [`t[:rufus_scheduler_time]` in timeout_jobs](https://github.com/jmettraux/rufus-scheduler/blob/v3.1.1/lib/rufus/scheduler.rb#L589-L606) that is nil (which is [covered by the specs](https://github.com/jmettraux/rufus-scheduler/blob/v3.1.1/spec/scheduler_spec.rb#L428)) for some reason.

Some more information. The project is using Ruby 2.2.2p95 and rufus-scheduler 3.1.1. I have tried to extract the relevant parts (and `Gemfile.lock`) of the project into this gist: https://gist.github.com/dentarg/7e2e9cf207d8751c0e48

We are using the [advanced lock scheme](https://github.com/jmettraux/rufus-scheduler#advanced-lock-schemes) with zookeeper, and that's seem to be where the issue lies. The zk gem has logging as a dependency and that gem does quite some magic with threads: https://github.com/TwP/logging/blob/logging-1.8.2/lib/logging/diagnostic_context.rb#L281-L328

Not sure where to go from here, maybe let @slyphon, @eric and @TwP know about this can help.

As I said, I have not tried to reproduce it, as it is not a big problem (currently), so I'm likely not going to try. Just wanted to share the information I have and see if someone do understand what is going on. No worries if you do not care about this. :)

**Comment by jmettraux** [comment]
Hello,

I think there is no need to look for a solution in the direction of Zookeeper or Logging.

I simplified the timeout checking code: https://github.com/jmettraux/rufus-scheduler/blob/62bd931bb550a5a4ec1c1525ee44f6555c5cf728/lib/rufus/scheduler.rb#L591-L606

The 3 values now have to be present (previously only the 2 first) in order for a thread to be evaluated for a potential timeout.

I think that your issue happened when the code was considering a thread just finishing its service. Sometimes (twice a year?) _job and _timeout (and _time) are set, but a few operations and a "thread switch" later, the _time value has been set to nil ( https://github.com/jmettraux/rufus-scheduler/blob/62bd931bb550a5a4ec1c1525ee44f6555c5cf728/lib/rufus/scheduler/jobs.rb#L269-L271 ) and the NoMethodError is raised.

Closing. Tell me if you need a 3.1.3 release.

Many thanks!

**Comment by dentarg** [comment]
Sure, a 3.1.3 release would be nice, then I can really leave this behind internally :). But there's no immediate hurry.

Thank you for the quick response, and the nice rufus-scheduler gem.

**Comment by jmettraux** [comment]
OK, 3.1.3 released. Thanks again!
