### ISSUE TITLE
Sometimes thread is generate too much...

### ISSUE THREAD

**Issue by jun85664396** [jmettraux/rufus-scheduler#159]
Hi there.
I using rufus-scheduler + unicorn
Sometimes thread is generate too much....
I don't understand this problem.
see my below screenshot!
![2015-07-20 10 15 41](https://cloud.githubusercontent.com/assets/7875341/8768825/4d1008c6-2ec8-11e5-84a8-85fbfd32e96d.png)
..after die ... XD
![2015-07-20 10 20 30](https://cloud.githubusercontent.com/assets/7875341/8768851/fb0dd8a4-2ec8-11e5-92f1-4c66d1b83407.png)
in Work.scheduling
![2015-07-20 10 28 31](https://cloud.githubusercontent.com/assets/7875341/8768885/1e11cbca-2eca-11e5-916a-d774bbaa04f3.png)

the scheduler executing every 2 minute, thread explosively increase and die.
but my work doesn't need these too many threads.
I don't know why increase threads like this.
Thanks for your time :D

**Comment by jmettraux** [comment]
Hello,

your second screenshot says:
```ruby
if scheduler.work_threads.size > (scheduler.max_work_threads.to_i - 50)
  scheduler.max_work_threads += 30
end
```
You are increasing the max threads by yourself... You are inviting the explosion on yourself.

Why do need to wrap a `Rufus::Scheduler.singleton.at` within the `Rufus::Scheduler.singleton.every`? Why don't you simply call
```ruby
begin
  work.child_job.child_jobs
rescue => e
  p e
end
```
?

I really don't know what else `Work.scheduling` does, but you should write simpler, more straightforward code.

**Comment by jun85664396** [comment]
The main cause is idle threads.
the threads hasn't disappeared when they're job finished.
It bring bottleneck and soon my work server died.
so i tried to add the code that kill idle threads in every 2 minute.

**Comment by jun85664396** [comment]
resolved!
The main cause is idle threads.
the threads hasn't disappeared when they're job finished.
It bring bottleneck and soon my work server died.
so i tried to add the code that kill idle threads in every 2 minute.
```
scheduler =  Rufus::Scheduler.singleton(:max_work_threads => 100, :lockfile => ".rufus-scheduler.lock")
scheduler.work_threads(:vacant).each do |x| 
    Thread.kill x
end 
```

**Comment by jmettraux** [comment]
Hello,

well done.

The normal scenario would be to leave the work_threads pegged at 100 or some other positive integers and leave it like that, not adding 30 to the max whenever the max was nearing...

I think that simply removing your auto `+30` should have fixed the issue in the first place.

Best regards.
