### ISSUE TITLE
Possibility to pass day of week in first_at

### ISSUE THREAD

**Issue by mrvovanness** [jmettraux/rufus-scheduler#161]
I just want to ask - is a possibility to pass day of week to first_at. I use resque-scheduler for dynamic scheduling in such manner:
```
config[:every] = ['3w', {first_at: 'some day of week'}]
```
I just read docs on rufus-scheduler and resque-scheduler and didn't find answer.

**Comment by jmettraux** [comment]
Hello,

if the Chronic gem is present, rufus-scheduler >= 3.0 should accept something like
```ruby
require 'chronic'
# ...
config[:every] = [ '3w', { first_at: 'next monday at 12:00' } ]
```

But, iirc, resque-scheduler still uses rufus-scheduler < 3.0, so you're probably better off with something like:
```ruby
require 'chronic'
# ...
config[:every] = [ '3w', { first_at: Chronic.parse('next monday at 12:00') } ]
```

Best regards.
