### ISSUE TITLE
six-field cronlines with division syntax in the seconds field lose the beat

### ISSUE THREAD

**Issue by jhw-at-prosperworks-com** [jmettraux/rufus-scheduler#163]
Howdy, thanks for building a terrifically useful gem.

Unfortunately, I've found an unexpected behavior: cronlines such as '*/10 * * * * *' exhibit a strange behavior where they lose their rhythm after a few beats.

It seems that the logic in Cronline.next_second() has a discontinuity when time.sec exceeds secs.last: it adds a minute, rather than rolling back around to secs.first.

I don't have a fix yet (apologies - still working on it) but I am about to post a PR which highlights the bug.

**Comment by jhw-at-prosperworks-com** [comment]
The PR which demonstrates this issue is PR https://github.com/jmettraux/rufus-scheduler/pull/164.

**Comment by jhw-at-prosperworks-com** [comment]
I believe the problem comes down to this line in Cronline.next_second(): https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler/cronline.rb#L297

It seems all of the new specs which I added, which fail, involve going through that early return logic.  All the existing specs, which pass, fall through to the bottom of the method.

**Comment by jmettraux** [comment]
Thanks a lot for the excellent report. Give me a few days.

**Comment by jhw-at-prosperworks-com** [comment]
You bet!

**Comment by jmettraux** [comment]
I fixed the issue and released 3.1.4.

Thanks a lot! Have a nice week-end!

**Comment by jhw-at-prosperworks-com** [comment]
Wow, that's awesome.  Thanks!
