### ISSUE TITLE
Not working on rails 4 server running on daemon mode (-d)

### ISSUE THREAD

**Issue by messuti-edd** [jmettraux/rufus-scheduler#165]
Tested with the simple example from the readme:

```ruby
# config/initializers/scheduler.rb

require 'rufus-scheduler'

s = Rufus::Scheduler.singleton

s.every '1m' do
  Rails.logger.info "hello, it's #{Time.now}"
end
```

When starting the rails server with `rails server -d &`, rufus scheduled tasks won't fire up.

I've found out that adding `s.join` at the end of the script fixes the issue when running as daemon, but when running just as `rails server` the web server won't work, so I guess this is not intended to be used with rails.

**Comment by jmettraux** [comment]
Could you please tell which web server you're running Rails on?
Then, could you please give here the first 100 lines of the Rails log you obtain?
Could you please state what operating system you're running on and what version of Ruby?
Anything else you forgot to mention?

Thanks in advance.

**Comment by jmettraux** [comment]
> I've found out that adding s.join at the end of the script fixes the issue when running as daemon, but when running just as rails server the web server won't work, so I guess this is not intended to be used with rails.

Indeed `s.join` is intended only for stand-alone scripts.

**Comment by messuti-edd** [comment]
Server: thin
OS: We have reproduced this on MacOS and Linux Ubuntu
Ruby version: 1.9.3p551

The first lines of the server booting not in daemon mode:
```
=> Booting Thin
=> Rails 4.2.0 application starting in development on http://localhost:3003
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:3003, CTRL+C to stop
2015-09-10 18:03:00.234 [INFO ] This is a rufus scheduled task (pid:45119)
2015-09-10 18:03:31.731 [INFO ] This is a rufus scheduled task (pid:45119)
```

The first lines of the log in daemon mode:
```
2015-09-10 18:06:06.775 [INFO ] Setting up scheduled jobs... (pid:45152)
```

**Comment by jmettraux** [comment]
Have you tried flushing the logger?
Have you tried with Webrick (not Thin)?

**Comment by jmettraux** [comment]
Interesting, "Setting up scheduled jobs..." appears in daemon mode, but not in "normal" mode.

**Comment by jmettraux** [comment]
OK, I guess the thread for the scheduler is created before the `-d` daemon double fork. Looking up...

**Comment by messuti-edd** [comment]
Just tried with Webrick, seeing the same behavior.

**Comment by jmettraux** [comment]
I tested on Rails 3.2.22 / OSX and seeing the same behaviour. Now, what I don't understand is why nobody did complain in all those years. One possible explanation would be that only a few people use `-d`.

**Comment by messuti-edd** [comment]
It surprised me too not to find an issue here about it already, I guess `-d` is not as commonly used as I thought.

**Comment by messuti-edd** [comment]
I did found one or two posts on stackoverflow about it though.

**Comment by jmettraux** [comment]
Links?

**Comment by jmettraux** [comment]
I like runit http://www.mikeperham.com/2014/07/07/use-runit/ to run stuff. I never daemonize development servers.

**Comment by jmettraux** [comment]
Another solution would be to use Unicorn and start the scheduler in an `after_fork` block.

**Comment by jmettraux** [comment]
Just tried on OSX with Unicorn 4.9.0 and `bundle exec unicorn -D`, without bothering about writing an `after_fork` and it works out of the box. The main process forks a worker process and that worker process hosts the scheduler thread.

I will write a piece of documentation to close this issue.

**Comment by messuti-edd** [comment]
OK thanks for the support @jmettraux :)
