### ISSUE TITLE
enhance job id uniqueness

### ISSUE THREAD

**Issue by jmettraux** [jmettraux/rufus-scheduler#170]
build on gh-169

**Comment by kssminus** [comment]
@jmettraux 
This issue occurred on jruby-1.7.16.1

**Comment by jmettraux** [comment]
@kssminus what OS and version?

**Comment by jmettraux** [comment]
Unfortunately, the `SecureRandom` approach doesn't succeed at the `10_000` test.

<img width="710" alt="screen shot 2015-09-30 at 15 41 30" src="https://cloud.githubusercontent.com/assets/3624/10186163/e974abd2-6789-11e5-9f69-2ba7fc49fa4b.png">

**Comment by jmettraux** [comment]
@kssminus Many thanks!!
