### ISSUE TITLE
Scheduler is running two three times.

### ISSUE THREAD

**Issue by shilpi230** [jmettraux/rufus-scheduler#171]
I am using scheduler to run some sidekiq jobs by using cron 
```scheduler.cron("30 15 * * *") do
 	SampleWorker.perform_async
end```

But i have no clue why its calling SampleWorker sometimes two times sometimes three times. ?

**Comment by jmettraux** [comment]
Hello,

please indicate:

* Ruby version
* Operating System and its version
* rufus-scheduler version

If you are running this in a framework (for example Ruby on Rails or Sinatra) please indicate what framework and what version.
If running a web application please indicate on what server you're running it (Unicorn, Passenger, Webrick or something else).

Please explain thouroughly what you mean by:
> calling SampleWorker sometimes two times sometimes three times

From my point of view it should be calling `SampleWorker.perform_async` once per day at 15:30
What are you expecting?

I would suggest you do something like:
```ruby
scheduler.cron("30 15 * * *") do
  p [ 'performing...', scheduler.hash, $$ ]
  SampleWorker.perform_async
end
```

The `p` will log the instance hash for the scheduler and the current PID, so we can see if you're running multiple scheduler instances and or multiple processes.

Thanks in advance for the detailed information.

This is important: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html Please do read it!

**Comment by jmettraux** [comment]
I will close this non-issue tomorrow.

**Comment by shilpi230** [comment]
Hey sorry @jmettraux sorry for late reply i was doing the same thing but i have no idea instead calling that worker one time it was calling it more than once so instead of calling the worker class i directly called the perform function with proper arguments, So now issue is solved :)

**Comment by jmettraux** [comment]
Ah, good news :-)

Well done :+1:
