### ISSUE TITLE
cron DST autumn transition issue America/Los Angeles

### ISSUE THREAD

**Issue by jmettraux** [jmettraux/rufus-scheduler#176]
As claimed in #175

**Comment by jmettraux** [comment]
Hello @alyssa 

`spec/cronline_spec.rb:919` is not failing on my machine for those two Ruby versions:

```
$ uname -a
Darwin satsuma.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
$ ruby -v
ruby 1.9.3p547 (2014-05-14) [x86_64-darwin14.5.0]
$ chruby 2.1
$ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]  
```

What are you running on and with what version of Ruby (development and production ("Square" I guess)) ? Thanks in advance

**Comment by alyssa** [comment]
@jmettraux that is no longer failing for me. the failing spec I pasted earlier was a bug on my part (pushed a fixed). These are the failing specs I see now:

```
Failures:

  1) Rufus::Scheduler::CronLine fall time correctly increments every minute through a DST transition
     Failure/Error: expect(points).to eq(
       
       expected: ["01:58:00l 08:58:00u", "01:59:00l 08:59:00u", "01:00:00l 09:00:00u", "01:01:00l 09:01:00u"]
            got: ["01:58:00l 09:58:00u", "01:59:00l 09:59:00u", "02:00:00l 10:00:00u", "02:01:00l 10:01:00u"]
       
       (compared using ==)
     # ./spec/cronline_spec.rb:938:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `call'
     # ./spec/spec_helper.rb:67:in `in_zone'
     # ./spec/cronline_spec.rb:926:in `block (3 levels) in <top (required)>'

  2) Rufus::Scheduler::CronLine fall time correctly decrements every minute through a DST transition
     Failure/Error: expect(points).to eq(
       
       expected: ["01:01:00l 09:01:00u", "01:00:00l 09:00:00u", "01:59:00l 08:59:00u", "01:58:00l 08:58:00u"]
            got: ["01:01:00l 09:01:00u", "01:00:00l 09:00:00u", "01:59:00l 09:59:00u", "01:58:00l 09:58:00u"]
       
       (compared using ==)
     # ./spec/cronline_spec.rb:970:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:67:in `call'
     # ./spec/spec_helper.rb:67:in `in_zone'
     # ./spec/cronline_spec.rb:958:in `block (3 levels) in <top (required)>'
```

**Comment by jmettraux** [comment]
Thanks for the update @alyssa, could you please answer my Ruby/OS versions question?

**Comment by alyssa** [comment]
@jmettraux ah missed that. answers below:

```
➜  rufus-scheduler git:(alyssa/failing+dst+specs) uname -a
Darwin arp.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
➜  rufus-scheduler git:(alyssa/failing+dst+specs) ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

**Comment by jmettraux** [comment]
Hello @alyssa ,

if you could take the time to look at the fix, from the point of view of your specs and the specs I added around it.

I made sure the "every minute" cron didn't jump one hour. According to the specs you added, I think that is what you observed and want fixed.

Thanks in advance.

**Comment by alyssa** [comment]
@jmettraux Thanks for the fix. I left a comment on 1eb484345eb3aac7478fdbb058cb88af9ab3fa43. Can you open a PR so I can see if specs are passing/failing?

**Comment by jmettraux** [comment]
Hello,

specs are passing: https://travis-ci.org/jmettraux/rufus-scheduler (click on the "build: passing" badge on top of the readme).

In reply to your note:

The successful expectation shows that the transition is hit (-7 becomes -8). But I will rework this spec so that it's more explicit.

**Comment by jmettraux** [comment]
In reply to your note (2):

Please look at https://github.com/jmettraux/rufus-scheduler/blob/8c39fc3d5503a08da5f524cec080c4dc4cf38b64/spec/cronline_spec.rb#L1036-L1066 for the latest version of this spec.

It shows the 0150 PDT to 0100 PST transition (as fixed by the set of fix commits).

**Comment by alyssa** [comment]
@jmettraux ah, didn't realize the commits linked here are already in master. The clarification makes it much easier to read. thanks!

can we cut a release?

**Comment by jmettraux** [comment]
Released. Many thanks!
