### ISSUE TITLE
rspec tests -- not passing on vanilla checkout

### ISSUE THREAD

**Issue by travis-bear** [jmettraux/rufus-scheduler#178]
I hit this on mac and linux, using ruby 2.1 and 2.0, on bash and zsh.  Is there additional config required to get this working?

Thanks!

-Travis

[master][~/git/community/rufus-scheduler]$ bundle exec rspec                                  
RUBY_VERSION: 2.0.0
RUBY_PLATFORM: x86_64-linux
.......................................................FF...................................................................................................................................................................*.................*.........................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Rufus::Scheduler#at accepts an ActiveSupport time thinggy
     # Not yet implemented
     # ./spec/schedule_at_spec.rb:143

  2) Rufus::Scheduler#schedule_in accepts an ActiveSupport .from_now thinggy
     # Not yet implemented
     # ./spec/schedule_in_spec.rb:73

Failures:

  1) Rufus::Scheduler::CronLine#matches? matches correctly when there is a sun#2 involved
     Failure/Error: expect(cl(line).matches?(time)).to eq(true)
       
       expected: true
            got: false
       
       (compared using ==)
     # ./spec/cronline_spec.rb:54:in `match'
     # ./spec/cronline_spec.rb:641:in `block (3 levels) in <top (required)>'

  2) Rufus::Scheduler::CronLine#matches? matches correctly when there is a L involved
     Failure/Error: expect(cl(line).matches?(time)).to eq(true)
       
       expected: true
            got: false
       
       (compared using ==)
     # ./spec/cronline_spec.rb:54:in `match'
     # ./spec/cronline_spec.rb:647:in `block (3 levels) in <top (required)>'

Finished in 3 minutes 29.5 seconds (files took 0.17997 seconds to load)
344 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/cronline_spec.rb:639 # Rufus::Scheduler::CronLine#matches? matches correctly when there is a sun#2 involved
rspec ./spec/cronline_spec.rb:645 # Rufus::Scheduler::CronLine#matches? matches correctly when there is a L involved

**Comment by jmettraux** [comment]
Hello,

Travis-CI tells me Ruby 2.1 and 2.2 are OK: https://travis-ci.org/jmettraux/rufus-scheduler

My OSX succeeds and says:
```
$ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
$ uname -a
Darwin satsuma.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

My Debian GNU/Linux succeeds and says:
```
$ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
$ uname -a
Linux dejima 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
```

I manage my Ruby with https://github.com/postmodern/chruby and build them with https://github.com/postmodern/ruby-install#readme

Sorry.
