### ISSUE TITLE
Listing all active/waiting schedulers

### ISSUE THREAD

**Issue by kotowick** [jmettraux/rufus-scheduler#184]
In Rails, it it possible to list all "schedulers" (in perhaps a service file)?

With Delayed Job, for example, we could run Delayed::Job.all and this would return a list of all active/waiting jobs through Delayed Job.

**Comment by jmettraux** [comment]
I guess you want to list "job" instances and not "scheduler" instances.

https://github.com/jmettraux/rufus-scheduler#looking-up-jobs

Maybe my guess is wrong. If so, rephrase your question.

Best regards.
