### ISSUE TITLE
Permission denied on lockfile when loading Rails Console

### ISSUE THREAD

**Issue by emaiax** [jmettraux/rufus-scheduler#186]
I've configured rufus-schedule to use some lockfile on production just like these:

```ruby
require "rufus-scheduler"

options = Rails.env.test? ? {} : { lockfile: "/tmp/.rufus-scheduler.lock", discard_past: false }
s = Rufus::Scheduler.singleton(options)
```

And when I try to access the production console:

```console
$ bundle exec rails c
/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.10/lib/rufus/scheduler/locks.rb:66:in `initialize': Permission denied @ rb_sysopen - /tmp/.rufus-scheduler.lock (Errno::EACCES)
	from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.10/lib/rufus/scheduler/locks.rb:66:in `new'
	from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.10/lib/rufus/scheduler/locks.rb:66:in `lock'
	from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.10/lib/rufus/scheduler.rb:107:in `initialize'
	from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.10/lib/rufus/scheduler.rb:116:in `new'
	from /opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.1.10/lib/rufus/scheduler.rb:116:in `singleton'
	from /var/app/current/config/initializers/scheduler.rb:4:in `<top (required)>'
```

That means my app runs under a different user than my ssh user, but I think my scheduler shouldn't be loaded on console. Also, we use this filelock because we run Puma with a few threads and they've been starting the scheduler multiple times.

Is there any approach that I've been missing?

**Comment by jmettraux** [comment]
This is more a Ruby on Rails question than a "rufus-schedule" question.

> but I think my scheduler shouldn't be loaded on console

You're in charge, you could take inspiration from http://stackoverflow.com/questions/4603704/how-can-i-detect-if-my-code-is-running-in-the-console-in-rails-3 and avoid scheduling when the initializer is run in console mode.

I don't know what version of Ruby on Rails you're using but tell me if that StackOverflow `if` block works and I'll add something to the Ruby on Rails section of rufus-scheduler's readme.

Thanks in advance.

**Comment by emaiax** [comment]
@jmettraux thanks, your tip actually worked for me.

>
You're in charge, you could take inspiration from http://stackoverflow.com/questions/4603704/how-can-i-detect-if-my-code-is-running-in-the-console-in-rails-3 and avoid scheduling when the initializer is run in console mode.

Thinking about it again, I guess you're right. The whole problem isn't the lockfile, but how I'm trying to do things with different permissions in this context.

Thanks for you time, man :rocket: :dancers:

**Comment by jmettraux** [comment]
You're welcome.

What version of Ruby on Rails are you using?

**Comment by emaiax** [comment]
Oh, I'm sorry. Ruby 2.2.2, Rails 4.2.5.

**Comment by jmettraux** [comment]
Thanks!

**Comment by jmettraux** [comment]
https://github.com/jmettraux/rufus-scheduler#avoid-scheduling-when-running-the-ruby-on-rails-console

Thanks again.

**Comment by anjali-sharma** [comment]
In accordance with the option to avoid scheduling when running the rails console, is there a similar option to avoid scheduling in other scenarios where the rails environment reloads, such as when running migrations and other utilities using 'rake'. Or perhaps, a way to restrict the scheduling to rails server only.

Thanks in  advance. :)

**Comment by jmettraux** [comment]
Hello,

I had a look at http://stackoverflow.com/questions/2467208/how-can-i-tell-if-rails-code-is-being-run-via-rake-or-script-generate

You could do something like:

```ruby
unless defined?(Rails::Console) || File.split($0).last == 'rake'
  
  # not called from the rails console nor from a rake task, do schedule!

  # scheduling...
end
```

**Comment by anjali-sharma** [comment]
This works perfect. Thanks a lot for the quick response. :)

**Comment by aesyondu** [comment]
Hi, I would like to add, if using bin/spring (https://stackoverflow.com/questions/39081940/determine-if-using-rails-console-or-server-when-using-spring):

```ruby
unless $PROGRAM_NAME.include?('spring') do
  # code
end
```

**rails 4.2.6
spring 2.0.0
rufus-scheduler 3.6.0**

When I use `bin/rails console` the `defined?(Rails::Console)` is false, so I used an alternative instead.

**Comment by jmettraux** [comment]
@aesyondu Thanks a lot!
