### ISSUE TITLE
Cannot load such file in production

### ISSUE THREAD

**Issue by dsvoba** [jmettraux/rufus-scheduler#187]
The gem does work in development environment, but in production unicorn log shows "`require': cannot load such file -- rufus-scheduler (LoadError)". Any idea?

**Comment by jmettraux** [comment]
http://ruby-doc.org/core-1.9.3/LoadError.html

Simply make sure that your production environment has access to rufus-scheduler, via its Gemfile or manually via its classpath.

Best regards.
