### ISSUE TITLE
Tests failing randomly

### ISSUE THREAD

**Issue by balasankarc** [jmettraux/rufus-scheduler#190]
Hi,
I have packaged rufus-scheduler for Debian, but it seems the tests are failing randomly.
See two logs below

1. http://paste.debian.net/359992/
2. http://paste.debian.net/360012/

This has caused an RC bug to be filed against it  - https://bugs.debian.org/809289

Do these tests depend on the time taken for running them? Or, if you can confirm that rufus-scheduler actually works (from all those other successful tests), I can disable the tests in Debian package and remove the RC bug.

**Comment by jmettraux** [comment]
Hello,

> Do these tests depend on the time taken for running them?

No.

> Or, if you can confirm that rufus-scheduler actually works

 https://travis-ci.org/jmettraux/rufus-scheduler <-- do you consider it a confirmation?

I will add Ruby 2.2.3 to Travis and see what happens.

**Comment by jmettraux** [comment]
Added 2.2.3 to https://travis-ci.org/jmettraux/rufus-scheduler and made sure to run that version 3 times. It was successful the 3 times.

I think it might be related to how Ruby is compiled, your infrastructure does it differently.

What version of Debian GNU/Linux are you using? Mine is a Jessie and I see only Ruby 2.1.

**Comment by balasankarc** [comment]
On 6 January 2016 2:30:42 am IST, John Mettraux <notifications@github.com> wrote:
>Added 2.2.3 to https://travis-ci.org/jmettraux/rufus-scheduler and made
>sure to run that version 3 times. It was successful the 3 times.
>
>I think it might be related to how Ruby is compiled, your
>infrastructure does it differently.
>
>What version of Debian GNU/Linux are you using? Mine is a Jessie and I
>see only Ruby 2.1.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jmettraux/rufus-scheduler/issues/190#issuecomment-169132666

The first log is from my local machine and second log is from official Debian build setup. Both runs Debian Unstable.

Anyway, seeing most of the tests run fine in those two logs, I am gonna temporarily disable the tests during bug so as to close the RC bug.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jmettraux** [comment]
OK, closing the issue here.

If the problem arises again in some form, I'll take the time to setup a test environment and try to fix that there.

Thanks!
