### ISSUE TITLE
Bundle error

### ISSUE THREAD

**Issue by maxrosecollins** [jmettraux/rufus-scheduler#196]
Not sure where to ask this question... here or [sidekiq-scheduler]( https://github.com/moove-it/sidekiq-scheduler)
I'm getting the following error 

```
Could not find rufus-scheduler-3.1.10 in any of the sources
Run `bundle install` to install missing gems.
```

The problem is this gem _is_ installed. I have tried removing it and reinstalling it but I keep getting the same error.

Any ideas?
Thanks in advance

**Comment by jmettraux** [comment]
Please try to run `bundle install`, then try again. Tell me then if the issue is solved or not.

**Comment by maxrosecollins** [comment]
Hi @jmettraux 

I tried that but it didn't work. I had to stop and start spring to fix the issue.
I can't imagine it has anything to do with rufus

**Comment by jmettraux** [comment]
OK, you're welcome.

**Comment by maxrosecollins** [comment]
Thanks for the quick response!!
