### ISSUE TITLE
subtracting from last day of the month

### ISSUE THREAD

**Issue by jonbcampos** [jmettraux/rufus-scheduler#197]
I'm trying to "0 0 L-15 * *" and I get a "couldn't parse". I'm trying to offset back from the last day of the month. Thoughts on how to achieve this?

**Comment by jmettraux** [comment]
Hello,

so you want to trigger something 15 days before the end of the months. I guess your requirements say "two weeks before the end of the month". Why not simply trigger on the 15th of each month?

I could implement `L-15` but it would conflict with entries like `4-6` (the 4th, 5th and 6th days).

Best regards.

**Comment by jmettraux** [comment]
You could also trigger on the 15th (30-25), the 16th (31-25), the 13th (28-15) and the 14th (29-15), then, within the triggered code, if it's really 15 days to the end of the month, go on with the triggering.

**Comment by jonbcampos** [comment]
I will look into those ideas. The reason that L-x is good is cause you
could always be sure to run x days from the end of the month whether you
are in a month with 28 days or 31 days.

**Comment by jmettraux** [comment]
You're welcome.

**Comment by jonbcampos** [comment]
Sorry, you caught me mid thought. Thank you very much for the quick
response.

**Comment by jmettraux** [comment]
Hello,

re-opening, I like the idea after all. I will implement it.

**Comment by jonbcampos** [comment]
You rock!

**Comment by jmettraux** [comment]
Please review.

Thanks in advance.

**Comment by jonbcampos** [comment]
Just read all the commits and I think it looks good. Very creative solution
using the negative values and ranges. I don't know if you care to call out
in your documentation that this functionality is how to mimic the cron
expression "L". Other than that I think you've knocked it out of the park.

**Comment by jmettraux** [comment]
@jonbcampos wrote:
> I don't know if you care to call out in your documentation that this functionality is how to mimic
> the cron expression "L".

Well, it's not mimicking "L", else I wouldn't have implemented it since rufus-scheduler already supports "L": https://github.com/jmettraux/rufus-scheduler#l-last-day-of-month 

OK. Thanks a lot.
