### ISSUE TITLE
Run job multiple times

### ISSUE THREAD

**Issue by nazrulcse** [jmettraux/rufus-scheduler#199]
I am using rufus-scheduler for a heroku application. I see it seems running multiple time. Is there any way to prevent this to run single time. I already tried 
```ruby 
scheduler = Rufus::Scheduler.new(:lockfile => ".rufus-scheduler.lock")
unless scheduler.down?
  scheduler.cron '00 12 * * *' do
    Rails.logger.info "Running: 00 12 * * *"
    FreeTrial.free_trial_sixteen_day_email
  end
end
 ```
but doesn't work.

**Comment by nazrulcse** [comment]
This is my config/initializers/scheduler.rb file
```ruby
require 'rufus-scheduler'

#scheduler = Rufus::Scheduler.new
scheduler = Rufus::Scheduler.new(:lockfile => ".rufus-scheduler.lock")

unless scheduler.down?
  scheduler.cron '30 10 * * *' do
    Rails.logger.info "Running: 30 10 * * *"
    FreeTrial.free_trials_to_deactivate
  end

  scheduler.cron '00 11 * * *' do
    Rails.logger.info "Running: 00 11 * * *"
    FreeTrial.free_trial_seven_day_email
  end

  scheduler.cron '30 11 * * *' do
    Rails.logger.info "Running: 30 11 * * *"
    FreeTrial.free_trial_thirteen_day_email
  end

  scheduler.cron '00 12 * * *' do
    Rails.logger.info "Running: 00 12 * * *"
    FreeTrial.free_trial_sixteen_day_email
  end

  scheduler.every '28m' do
    Article.schedule_publish
  end
end
```
Every email goes three times, I am using heroku server, rails 3.1.7, ruby 2.0.0, rufus-scheduler (3.2.0)

Thanks

**Comment by jmettraux** [comment]
Hello,

I am no Heroku specialist, but I think your dynos do not share files, hence your rufus-scheduler instances are each seeing their own ".rufus-scheduler.lock" files.

I would suggest you read the documentation about scheduling Heroku has published: 
* https://devcenter.heroku.com/articles/scheduler#scheduling-jobs
* https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes#custom-clock-processes

That second link is interesting because it shows how you can dedicate a dyno to a clockwork or a rufus-scheduler process.

If that doesn't help, you should find a way to communicate between your dynos and then build a customer locker for rufus-scheduler, following the (trivial) example at https://github.com/jmettraux/rufus-scheduler#scheduler_lock

I hope it helps. Best regards.

**Comment by jmettraux** [comment]
> Every email goes three times, I am using heroku server, rails 3.1.7, ruby 2.0.0, rufus-scheduler (3.2.0)

Do you have 3 dynos running your application?

**Comment by jmettraux** [comment]
Another question: are the 3 emails coming from the same scheduler or is there 1 email for 3 schedulers?

**Comment by nazrulcse** [comment]
My application running 3 dynos, and scheduler running three times and send 1 email per scheduler. Here is the log for running three times 
2016-02-29T12:00:00.166183+00:00 app web.2 - - **"Running: 00 12 * * *"** 
325 <158>1 2016-02-29T12:00:00.156586+00:00 heroku router - - at=info method=GET path="/assets/kaia_theme-77255cf366b84c4ccab220c38f942475.css" host=shawnmc.cool request_id=481a5143-bf3a-4e78-968c-27aac065a555 fwd="104.238.169.21" dyno=web.2 connect=0ms service=12ms status=200 bytes=66851
114 <190>1 2016-02-29T12:00:00.059194+00:00 app web.1 - - **"Running: 00 12 * * *"**
154 <190>1 2016-02-29T12:00:00.079325+00:00 app web.1 - -   Rendered free_trial_reminders/sixteen_day.html.erb (1.1ms)
94 <190>1 2016-02-29T12:00:00.206143+00:00 app web.1 - -
154 <190>1 2016-02-29T12:00:00.215510+00:00 app web.1 - -   Rendered free_trial_reminders/sixteen_day.html.erb (0.4ms)
133 <190>1 2016-02-29T12:00:00.206166+00:00 app web.1 - - Sent mail to rdenis91@gmail.com (125ms)
154 <190>1 2016-02-29T12:00:00.181367+00:00 app web.2 - -   Rendered free_trial_reminders/sixteen_day.html.erb (0.8ms)
326 <158>1 2016-02-29T12:00:00.316019+00:00 heroku router - - at=info method=GET path="/assets/application-43cbf4d6bbfa6493500db575b6c1c2c5.js" host=shawnmc.cool request_id=96ac11f7-80f4-4273-8fcf-e47fdaf2c061 fwd="104.238.169.21" dyno=web.2 connect=0ms service=34ms status=200 bytes=476263
117 <190>1 2016-02-29T12:00:00.047453+00:00 app worker.1 - - **"Running: 00 12 * * *"**
157 <190>1 2016-02-29T12:00:00.080318+00:00 app worker.1 - -   Rendered free_trial_reminders/sixteen_day.html.erb (1.2ms)

**Comment by jmettraux** [comment]
OK, I would simply suggest to do something like in your initializer:

```ruby
if ENV['DYNO'] == 'worker.1'

  scheduler = Rufus::Scheduler.new

  scheduler.cron '00 12 * * *' do
    Rails.logger.info "Running: 00 12 * * *"
    FreeTrial.free_trial_sixteen_day_email
  end

  # ...
end
```

See (and upvote) http://stackoverflow.com/questions/26416213/schedule-rufus-scheduler-onto-worker-dyno-on-heroku

**Comment by jmettraux** [comment]
You're welcome.
