### ISSUE TITLE
method in helper class

### ISSUE THREAD

**Issue by federicolucca** [jmettraux/rufus-scheduler#200]
Hi everyone,

i define scheduler in app.rb,and the method called in the job in an helper of the app.Everything is ok scope and load order.

```ruby
scheduler = Rufus::Scheduler.new

scheduler.every '5s' do
  scheduler1h(nil)
  logger.info("scheduler call")
end
```

if i put all code of "scheduler1h" in the job,everything is ok,otherwise no.The scheduler does not work
Someone can help me

Federico

**Comment by jmettraux** [comment]
Hello,

I'm sorry but could you please indicate what is your context? What framework are you using?

John

**Comment by federicolucca** [comment]
Sorry,

Framework is Padrino v0.13. ,the gem version is the lastest.
in app.rb,the main file of the app class, i put the require "require 'rufus-scheduler' " and the code above.

The method in the helper is ok,i use the same method in some other controllers class of the app. 


Federico

**Comment by jmettraux** [comment]
OK, I have no experience with Padrino and clearly, this is a Padrino question, not a rufus-scheduler question.

What happens if you call `schedule1h(nil)` directly from app.rb? By "directly" I mean not wrapping it within a rufus-scheduler block.

**Comment by federicolucca** [comment]
ok the problem is the scope of the helpers in Padrino app.rb

Sorry for the mistake
Thanks for your time

**Comment by jmettraux** [comment]
OK, cool, well done!
