### ISSUE TITLE
then a job is invoked with .call, .running? does not show it as running

### ISSUE THREAD

**Issue by piavka** [jmettraux/rufus-scheduler#214]
Hey, I'm using the scheduler to run jobs on cron like schedules , and also have an option to invoke the jobs out of schedule which is implemented by calling the .call method of the job
however then job is invoked in such way the .running? shows that job is not running
is this by design or bug ?

**Comment by jmettraux** [comment]
Hello,

it's by lack of design.

**Comment by piavka** [comment]
@jmettraux  cool thanks 
when to expect a new gem release ? :)

**Comment by jmettraux** [comment]
Hello,

you're welcome, it's a bit thin for a release. Can you live with `job.trigger(Time.now)` for the time being? or can you simply leverage http://bundler.io/git.html for now?

**Comment by piavka** [comment]
i cannot use gems deps thought git in production since they are pita to make reliable fir automatic deploy , i might end building a gem and push it to local artifactory

BTW if job is unscheduled can i still use the  new run method? also can i schedule job back from unscheduled state to scheduled or i'd have to redefine it from scratch ?

**Comment by jmettraux** [comment]
> BTW if job is unscheduled can i still use the new run method?

I think so.

> also can i schedule job back from unscheduled state to scheduled or i'd have to redefine it from scratch ?

I think
```ruby
scheduler.instance_eval { @jobs.push(job) }
```
might work.

It could be formalised as
```ruby
class Rufus::Scheduler::Job
  def reschedule
    @scheduler.instance_eval { @jobs.push(self) }
  end
end
```

**Comment by piavka** [comment]
@jmettraux  the run methods works great and job is visible as .running?

unfortunately while job is unscheduled or paused (cronjob) invoking .run or .call methods does nothing, is there trick to invoke the job body while it's paused ?

**Comment by piavka** [comment]
@jmettraux i managed to do thiss with this hack

```
class Rufus::Scheduler::CronJob
  def trigger_out_of_schedule(time)
    return if (
      opts[:overlap] == false &&
      running?
    )

    @count += 1

    if opts[:blocking]
      do_trigger(time)
    else
      do_trigger_in_thread(time)
    end
  end
end
```

I'm now using it instead of the new *run* method too

if you think there is place for this to be merged , let me know and i'll do a PR
tnx

**Comment by jmettraux** [comment]
OK, let me think about it. I want a solution that work for any job.

**Comment by jmettraux** [comment]
Hello @piavka I've adopted your `#trigger_out_of_schedule` (renamed it to `#trigger_off_schedule`).

Please have a look and tell me if it's OK with you.

I'll probably add the `Job#reschedule` discussed above, then release a 3.3.0.

Thanks a lot!
