### ISSUE TITLE
Does rufus-scheduler directly use CRON?

### ISSUE THREAD

**Issue by 9mm** [jmettraux/rufus-scheduler#217]
I used to use the `clockwork` gem, but that maintainer deleted the entire repo for some reason...

I'm hosting on Heroku and I need a good clock process to schedule my jobs. Heroku doesn't allow direct access to `crontab` (apparently) so I can't use the `whenever` gem, and I see in your readme that it says your gem is "not a replacement for cron".

Is `rufus-scheduler` able to do the job?

I used to run Clockwork in my `Procfile` as such:

    clock: bundle exec clockwork config/clock.rb

I assume I would need to do something similar with `rufus-scheduler`?

**Comment by jmettraux** [comment]
Good morning,

> Does rufus-scheduler directly use CRON?

No. Rufus-scheduler doesn't use its host's cron daemon.

> I used to use the clockwork gem, but that maintainer deleted the entire repo for some reason...

The gem is still available at https://rubygems.org/gems/clockwork
You are right, @tomykaira deleted his Clockwork fork...

Nothing prevents you from using it from your Bundler file with something like `gem "clockwork"`.

> Is rufus-scheduler able to do the job?

I don't exactly know what the job is, so I can't answer.

> I assume I would need to do something similar with rufus-scheduler?

Not really, there's no concept of `config/clock.rb` in rufus-scheduler. There's more setup work for you to do.

Finally, you should have a look at Heroku's documentation. They provide a lightweight scheduler (best effort), see https://devcenter.heroku.com/articles/scheduler

Good luck and best regards.
