### ISSUE TITLE
daylight saving not considered with every '1d' job

### ISSUE THREAD

**Issue by macmeck** [jmettraux/rufus-scheduler#218]
I have set up a job using
` Rufus::Scheduler.singleton.schedule_every '1d'` 
which was running fine for quite a while. Starting last weekend when summer time ended, jobs are being triggered one hour earlier. I guess that daylight saving is not being considered properly here.

**Comment by jmettraux** [comment]
Hello,

> I guess that daylight saving is not being considered properly here.

"every 1d", for rufus-scheduler is equivalent to "every 24 * 3600 seconds". There is no consideration of daylight saving time at all.

Use `schedule_cron` instead.

Best regards.
