### ISSUE TITLE
Scheduler jobs remain after overwriting the scheduler object

### ISSUE THREAD

**Issue by helge000** [jmettraux/rufus-scheduler#219]
```ruby
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new
scheduler.every('2s') do
  puts 'Test'
end

scheduler = Rufus::Scheduler.new
# Test
# Test
# (...)

scheduler = nil
# Test
# Test
# (...)
```

If this behavior is by design, what is the reasoning?

```
# gem list --local rufus-scheduler 

*** LOCAL GEMS ***

rufus-scheduler (3.2.2)
```

**Comment by jmettraux** [comment]
Hello,

```ruby
t =
  Thread.new do
    sleep 3
    puts "hello!"
  end

t = nil

sleep 20
```

The thread continues to print "hello!" after the `t` **reference** is overriden.

If this behaviour is by design, what is the reasoning?

Best regards.

**Comment by helge000** [comment]
I was questioning the behavior of the library, not that of threads.

As a user of the library, I need to know how the library is implemented to correctly use it. What might be obvious to you was oblivious to me in this matter (I did only use it in a small part and did not pay enough attention, obviously).

I can see this might be next to impossible to implement, at least the `scheduler = nil` version; but you could mention it as a caveat in the doc:

### Warning
Since scheduler jobs are threaded, they will remain active even after the scheduler object is overwritten. You need to explicitly call `#shutdown` or `#unschedule` methods to remove active job threads.

Cheers,

**Comment by jmettraux** [comment]
Hello,

> I was questioning the behavior of the library, not that of threads.

And I am questioning your understanding of the programming language.

Do you understand that you are merely changing a pointer from a instance of `Rufus::Scheduler` to an instance of `NilClass`?

> the scheduler object is overwritten

There is no overwriting of the scheduler object. You have to understand that if you want to progress as a programmer.

All the best.

**Comment by helge000** [comment]
> There is no overwriting of the scheduler object. You have to understand that if you want to progress as a programmer.

It might surprise you, I do understand this; and even new this before opening this ticket. I know because of your thread example, how *you choose* to implement it. 

This is by design how threads work. *But also a pitfall*. A mention in the doc is the simplest way to solve the matter. I could open a PR if you like; just tell me the position.

**Comment by jmettraux** [comment]
No thanks.
