### ISSUE TITLE
Thread safety with regard to time zone handling

### ISSUE THREAD

**Issue by knu** [jmettraux/rufus-scheduler#220]
Rufus-scheduler introduced ZoTime in 3.1.0, and since then `ENV['TZ']` may get modified in run time, where other threads may be creating Time objects or spawning child processes.

So, my question is, when do ZoTime#time and ZoTime#utc have a chance to be called?  Is it only when a schedule is registered using a time zone in the cron line, or is there a chance to be re-evaluated when some event occurs?

**Comment by jmettraux** [comment]
Hello,

as you guessed `ZoTime#time` is called upon registering a cron schedule.

It is also called upon a `CronJob#next_time` or a `CronJob#previous_time`.

`ENV['TZ']` is consulted by cron jobs when there is no definite time zone in the cron string (upon creation and for `#next_time` and `#previous_time`. That might be a problem (maybe that's what prompted you to open this issue). One solution could be to keep track of the timezone at the point of creation of the `CronJob` instance.

I'd be glad to help once I know exactly what bothers you.

Best regards.

**Comment by knu** [comment]
Thanks for the quick reply!

I have a system that persistently runs a scheduler built with rufus-scheduler, and the system dynamically adds or deletes schedules upon a request via API.  Each schedule periodically invokes a specified job on a specified time/interval, and the process involves running an external command, making an HTTP request and accessing DB while executing jobs.

So, what I need here is make sure jobs are not affected by registration of new schedules.

**Comment by jmettraux** [comment]
Ah, I understand. Indeed, the calls to `ZoTime#in_zone` are problematic. I will study how to avoid using it. It's currently used in two places in ZoTime.

Thanks for reporting that. Please give me a few days.

**Comment by knu** [comment]
Great.  Thanks for taking the time!  Actually I was about to start working on a PR, but before that I just wanted to know what you'd think about the idea of fixing it.

**Comment by jmettraux** [comment]
OK, got it. I'd be glad to have a PR from you.

**Comment by knu** [comment]
After some investigation, I've found you need to add back the parser for TZ values.  TZInfo or ActiveSupport::TimeZone can parse timezone representations like `Asia/Tokyo` or `PST`, but not `JST-9`.  It is likely you could do that better. 😥

**Comment by jmettraux** [comment]
I will bring back the dependency on TZInfo and cook something based on it that doesn't touch `ENV['TZ']`.

Thanks again.

**Comment by jmettraux** [comment]
It's taking its time but it's starting to look good.

**Comment by jmettraux** [comment]
Hello, apart from a slight problem with JRuby, this transition is done.

If you have the time, please have a look https://github.com/jmettraux/rufus-scheduler/compare/781c009d97...184bd6ab347

Your comments are welcome.

Many thanks for making me realize the problem behind my `ENV['TZ']` approach.

I will close this issue soon. I'll release this as part of the upcoming 3.3.0

**Comment by knu** [comment]
Wow, this must have been a tough work!  Thanks!

I've deployed the current master to my personal installation and so far it's been working fine.

**Comment by jmettraux** [comment]
Thanks, closing for now !
