### ISSUE TITLE
Takes forever with invalid cron string

### ISSUE THREAD

**Issue by ramontayag** [jmettraux/rufus-scheduler#221]
Try this and it will run forever:

```ruby
Rufus::Scheduler::CronLine.new("0 0 0 * *").next_time(Time.now)
```

This should raise an error right?

**Comment by jmettraux** [comment]
What error should it raise?

**Comment by ramontayag** [comment]
I'm thinking invalid cron syntax or something like that. I can work on
this.

**Comment by jmettraux** [comment]
Actually, you are right.

```ruby
Rufus::Scheduler::CronLine.new("0 0 0 * *")
  # and
Rufus::Scheduler::CronLine.new("* * 0 * *")
```

should raise an `ArgumentError`, since day 0 is not allowed. The error should be raised on `CronLine#initialize`, not on `CronLine#next_time`.

I will fix that for the next release, after I'm done with gh-220.

Thanks a lot for reporting that!

**Comment by ramontayag** [comment]
Ok cool thanks ☺

**Comment by jmettraux** [comment]
Hello Ramon,

I made sure "day 0" is avoided. Please have a look and tell me if you spot anything off.

Many thanks!

John

**Comment by ramontayag** [comment]
Looks great. Thank you!
