### ISSUE TITLE
cannot determine timezone from nil (ArgumentError)

### ISSUE THREAD

**Issue by lovingyu** [jmettraux/rufus-scheduler#222]
hello, everyone

I have a problem, i'm in china , when i use rufus-scheduler 

```ruby
require 'rufus-scheduler'
scheduler = Rufus::Scheduler.new
 scheduler.in '2s' do
   puts Time.now
   puts 'Hello...Word'
 end
 scheduler.join
```

get a  error messge: 

```
C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.0/lib/rufus/scheduler/zotime.rb:41:in `initialize': cannot determine timezone from nil (ArgumentError)
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.0/lib/rufus/scheduler/zotime.rb:196:in `new'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.0/lib/rufus/scheduler/zotime.rb:196:in `now'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.0/lib/rufus/scheduler.rb:561:in `start'
	from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rufus-scheduler-3.3.0/lib/rufus/scheduler.rb:109:in `initialize'
	from 2.rb:16:in `new'
	from 2.rb:16:in `<main>'
```

my  Time.now.zone  is "中国标准时间" , it means 'China Standard Time'.

may someone help me to Solve it ? 
thank you very much.
ps: my english is not good ,sorry about that.

**Comment by jmettraux** [comment]
Hello,

what version of Windows are you using?
How did you install your Ruby on Windows?

Thanks in advance.

**Comment by lovingyu** [comment]
hi ,thank you for your reply
my windows version is window 10 
ruby version is : ruby 2.2.4p230 x64-mingw32
i use ruby installer  rubyinstaller-2.2.4-x64.exe
thanks

**Comment by jmettraux** [comment]
Investigating... It's related to gh-220. Please wait.

**Comment by jmettraux** [comment]
Quick question:

```ruby
require 'rufus-scheduler'

ENV['TZ'] = 'Asia/Shangai'

scheduler = Rufus::Scheduler.new
scheduler.in '2s' do
  puts Time.now
  puts 'Hello...Word'
end
#scheduler.join
sleep 3
```
Does it work for you?

**Comment by lovingyu** [comment]
sorry  ,it doesn't work ,same error.

**Comment by jmettraux** [comment]
Hello,

if you place in your `Gemfile`
```ruby
#gem 'rufus-scheduler'
gem 'rufus-scheduler', git: 'https://github.com/jmettraux/rufus-scheduler'
```
and try again
```ruby
require 'rufus-scheduler'

ENV['TZ'] = 'Asia/Shangai'

scheduler = Rufus::Scheduler.new
scheduler.in '2s' do
  puts Time.now
  puts 'Hello...Word'
end
#scheduler.join
sleep 3
```
Does it work?

**Comment by lovingyu** [comment]
hi , i update script like you do ,but it's also failed.
and i add a : puts ::TZInfo::Timezone.get(ENV['TZ']
error messge:
cannot load such file -- tzinfo/data/definitions/Asia/Shangai (TZInfo::InvalidTimezoneIdentifier)

and i open the tzinfo gem folder \tzinfo\data\definitions
it look like:
\America
\Australia
\Etc
\Europe
EST.rb  
UTC.rb

there is no Asia folder.

**Comment by jmettraux** [comment]
If you add to your Gemfile this
```ruby
gem 'tzinfo-data'
#gem 'rufus-scheduler'
gem 'rufus-scheduler', git: 'https://github.com/jmettraux/rufus-scheduler'
```
and try again, does it work?

**Comment by lovingyu** [comment]
hi , 
i add this  
gem 'tzinfo-data'
gem 'rufus-scheduler', git: 'https://github.com/jmettraux/rufus-scheduler'  
into my Gemfile, and run  bundle install   
but  it  blocked  on
Fetching https://github.com/jmettraux/rufus-scheduler
can not install  rufus-scheduler

**Comment by jmettraux** [comment]
Try again, or give me the complete Bundler error message and I'll help you debug that install issue.

**Comment by lovingyu** [comment]
hi ,this is the error message:
$ bundle install
Your Gemfile lists the gem tzinfo-data (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Fetching https://github.com/jmettraux/rufus-scheduler



maybe because i'm in china ,the netword is  in government charge

**Comment by jmettraux** [comment]
OK, does
```
git clone https://github.com/jmettraux/rufus-scheduler
```
in the terminal work for you?

**Comment by lovingyu** [comment]
it's cloning:
$ git clone https://github.com/jmettraux/rufus-scheduler
Cloning into 'rufus-scheduler'...

**Comment by lovingyu** [comment]
it's very slow  , 43% now ...
after is cloned ,what should i do next?
thanks

**Comment by jmettraux** [comment]
OK, then in your Gemfile use
```
gem 'tzinfo-data'
gem 'rufus-scheduler', git: 'path/to/your/cloned/rufus-scheduler/repository'
```
Please remove the previous ```gem 'tzinfo-data'``` and ```gem 'rufus-scheduler'``` entries.
Then try again when bundle install has succeeded.

**Comment by lovingyu** [comment]
hi ,i run bundle install 
...
Using rufus-scheduler 3.3.0 from H:/WestInfo/MySoft/MyApp/rufus-scheduler (at master@975a00e)
Installing tzinfo-data 1.2016.9
...
Bundle complete! 22 Gemfile dependencies, 74 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

when i  run  this:
require 'rufus-scheduler'
ENV['TZ'] = 'Asia/Shangai'
scheduler = Rufus::Scheduler.new
scheduler.in '2s' do
  puts Time.now
  puts 'Hello...Word'
end
#scheduler.join
sleep 3

error message:
C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rufus-scheduler (LoadError)
	from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from H:/WestInfo/MySoft/MyApp/test.rb:1:in `<main>'

**Comment by jmettraux** [comment]
I think you are doing
```
ruby test_file.rb
```
try with 
```
bundle exec ruby test_file.rb
```
instead and tell me what happens.

**Comment by lovingyu** [comment]
hi , i try it ,but same error
$ bundle exec ruby test.rb     
c:/Ruby22/lib/ruby/gems/2.2.0/bundler/gems/rufus-scheduler-975a00e7a093/lib/rufus/scheduler/zotime.rb:41:in `
initialize': cannot determine timezone from nil (ArgumentError)
        from c:/Ruby22/lib/ruby/gems/2.2.0/bundler/gems/rufus-scheduler-975a00e7a093/lib/rufus/scheduler/zoti
me.rb:196:in `new'
        from c:/Ruby22/lib/ruby/gems/2.2.0/bundler/gems/rufus-scheduler-975a00e7a093/lib/rufus/scheduler/zoti
me.rb:196:in `now'
        from c:/Ruby22/lib/ruby/gems/2.2.0/bundler/gems/rufus-scheduler-975a00e7a093/lib/rufus/scheduler.rb:5
61:in `start'
        from c:/Ruby22/lib/ruby/gems/2.2.0/bundler/gems/rufus-scheduler-975a00e7a093/lib/rufus/scheduler.rb:1
09:in `initialize'
        from test.rb:5:in `new'
        from test.rb:5:in `<main>'

**Comment by jmettraux** [comment]
If you run in your command line:
```
bundle exec ruby -e "require 'tzinfo'; z = TZInfo::Timezone.get('Asia/Shanghai') rescue 'no Shanghai 0'; p z; require 'tzinfo/data'; z = TZInfo::Timezone.get('Asia/Shanghai') rescue 'no Shanghai 1'; p z"
```
What does it tell you?

**Comment by jmettraux** [comment]
Maybe simplier:
```ruby
# save me in tztest.rb and run me with
#
#   bundle exec ruby tztest.rb
#

require 'tzinfo'
z = TZInfo::Timezone.get('Asia/Shanghai') rescue 'no Shanghai 0'
p z
require 'tzinfo/data'
z = TZInfo::Timezone.get('Asia/Shanghai') rescue 'no Shanghai 1'
p z
```

**Comment by lovingyu** [comment]
#<TZInfo::DataTimezone: Asia/Shanghai>
#<TZInfo::DataTimezone: Asia/Shanghai>

**Comment by jmettraux** [comment]
OK, my fault:

Can you change the line
```
ENV['TZ'] = 'Asia/Shangai'
```
to
```
ENV['TZ'] = 'Asia/Shanghai'
```
and try again? (```bundle exec ruby test.rb```)

Thanks in advance.

**Comment by lovingyu** [comment]
ok ,it's work fine 
oh,I had not noticed that too ...
thank u very much

**Comment by jmettraux** [comment]
OK, thanks a lot.
I will release a 3.3.1 with the fix and state in the documentation that setting `ENV['TZ']` might be necessary if `cannot determine timezone from nil (ArgumentError)` appears.

**Comment by jmettraux** [comment]
Thanks again!

**Comment by jmettraux** [comment]
Opening again, seems JRuby 1.9 mode isn't quite happy: https://travis-ci.org/jmettraux/rufus-scheduler/jobs/180833892

**Comment by sofiabravo103** [comment]
Hi, I got the cannot determine timezone from nil error and added the fixed suggested in de faqs but the error continuous in the line where I start rufus: 

`ArgumentError (cannot determine timezone from "VET" (etz:"America/Caracas",tnz:"VET",tzid:"constant")):`

What's going on?

**Comment by jmettraux** [comment]
> What's going on?

It's 6am and I'm having a coffee and contemplating and old issue getting hijacked.

.

@sofiabravo103 good morning, could you please open a new issue? If you think this new issue is related to the old, closed, issue here, please include a link to here and indicate why you think they are related.

In the new issue, please indicate on what operating system you are running. Please also indicate if you have the tzinfo-data gem included in your bundle (does it appear in your `Gemfile.lock`?).

Thanks in advance.
