### ISSUE TITLE
scheduler is  getting halt after first run

### ISSUE THREAD

**Issue by debbiswal** [jmettraux/rufus-scheduler#223]
Hi ,
I have installed 3.2.0 version of this gem(https://rubygems.org/gems/rufus-scheduler/versions/3.2.0).
I have tried to run the below code  :
```ruby
require 'rufus-scheduler'
scheduler = Rufus::Scheduler.new
scheduler.in '3s' do
  puts 'Hello... Rufus'
end
scheduler.join
```

But after printing first 'Hello...' statement , the scheduler halts.After 3 seconds it is not printing the 'Hello..' statement again.
Not sure about the issue.

Below is my system configuration :
-----------------------------------------
CentOS in Vagrant : CentOS Linux release 7.2.1511 (Core)
Ruby Version : ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
Below are the gems installed in my system :
bigdecimal (1.2.0)
bundler (1.13.6)
concurrent-ruby (1.0.2)
daemons (1.2.4)
i18n (0.7.0)
io-console (0.4.2)
json (1.7.7)
lps (0.2.1)
minitest (5.10.1, 5.9.1)
option_initializer (1.5.1)
psych (2.0.0)
rdoc (4.0.0)
redis (3.0.2)
rufus-scheduler (3.2.0)
thread_safe (0.3.5)
tzinfo (1.2.2)

**Comment by jmettraux** [comment]
Please upgrade to rufus-scheduler 3.3.1 and try again.

**Comment by jmettraux** [comment]
Well, no need to upgrade...

try with
```ruby
require 'rufus-scheduler'
scheduler = Rufus::Scheduler.new
#scheduler.in '3s' do
scheduler.every '3s' do
  puts "Hello... Rufus #{Time.now.inspect}"
end
scheduler.join
```

`scheduler.in '3s'` will run once after 3 seconds. `scheduler.join` will let the current (here main) Ruby thread join the scheduler thread so that the Ruby process doesn't terminate unless expressly told so.

Best regards.
