### ISSUE TITLE
A distributed locking mechanism?

### ISSUE THREAD

**Issue by bbozo** [jmettraux/rufus-scheduler#224]
Hi all :)

I come from here https://github.com/moove-it/sidekiq-scheduler/issues/156 and I'm wondering if there's some good way of implementing custom locking mechanisms, for example a distributed lock via Redis?

It seems like there's some kind of anticipation of this feature already going on https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler/locks.rb but I found nothing in the docs so I'd like to know more :)

**Comment by bbozo** [comment]
I see it now! :) https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler.rb#L101 thank you

**Comment by jmettraux** [comment]
Linking to the documentation for the sake of completeness: https://github.com/jmettraux/rufus-scheduler#scheduler_lock
