### ISSUE TITLE
error when using with Rails 5

### ISSUE THREAD

**Issue by lovingyu** [jmettraux/rufus-scheduler#227]
hi, i try to use rufus in rails 5 ,but there have a problem:
  
  $scheduler.at st.sc_time do
         somemethod() 
  end
  $scheduler.join
 
  def somemethod()
     files=AutoUploadfile.where(:xmid=>session[:pr_id],:ntype=>0)
  end
 
AutoUploadfile is a model of database table .  
when i run the script , it's  blocked  here  :  files=AutoUploadfile.where(:xmid=>session[:pr_id],:ntype=>0)
and there is no response ,but i run this code in other program,  it's works fine.
so i wanna to kown  if  it's rufus problem ?
 
thanks

**Comment by jmettraux** [comment]
Hello,

what is the complete error message?

Please give me something like:
```
NoMethodError: undefined method `[]' for nil:NilClass
./lib/fugit/nat.rb:41:in `parse'
./spec/nat_spec.rb:27:in `block (4 levels) in <top (required)>'
/Users/jmettraux/.gem/ruby/2.2.5/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `load'
/Users/jmettraux/.gem/ruby/2.2.5/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/jmettraux/.gem/ruby/2.2.5/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:27:in `run'
/Users/jmettraux/.gem/ruby/2.2.5/gems/bundler-1.13.5/lib/bundler/cli.rb:332:in `exec'
```

Also, what version of Ruby? What operating system? What version of rufus-scheduler?

Thanks in advance.

**Comment by jmettraux** [comment]
Also, you are talking about Rails 5. Are you implying it works with Rails 4 or 3 ?

**Comment by jmettraux** [comment]
Also, what do you mean by "it's blocked here"? The whole application is blocked?

**Comment by lovingyu** [comment]
hi,  ruby version 2.2 
 this is code 

          puts "-----------------------"
          puts runtime
          puts st.sc_time
          puts "-----------------------"
          if st.sc_time>runtime then
            $scheduler.at st.sc_time do
              puts '=================='
              puts 'startjob...'
              files=AutoUploadfile.where(:xmid=>session[:pr_id],:ntype=>0)
              puts files.count
              puts '=================='
            end
          end
       end
       $scheduler.join


and there is no error message , just no reponse：
-----------------------
2017-01-04 14:53:36 +0800
2017-01-04 14:54:00 +0800
-----------------------
==================
startjob...

**Comment by jmettraux** [comment]
Other question: what Ruby server are you running your Rails 5 on top of? Passenger? Unicorn? Puma? Webrick?

**Comment by lovingyu** [comment]
Puma

**Comment by jmettraux** [comment]
JRuby or MRI Ruby? What version?

**Comment by lovingyu** [comment]
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]   
windows 10

**Comment by lovingyu** [comment]
files=AutoUploadfile.where(:xmid=>session[:pr_id],:ntype=>0)
 this  worked fine  in other program, but  in here  it doesn't work ,i wanna kown why .

**Comment by jmettraux** [comment]
Remove the
```ruby
$scheduler.join
```
line and try again. This line is only for standalone scripts, not for schedulers running *inside* of the Rails application.

Please tell me what happens (or not) then.

**Comment by lovingyu** [comment]
it's worked !  thanks a lot .

**Comment by jmettraux** [comment]
You're welcome. Have a nice day!
