### ISSUE TITLE
every job with :first_at triggering twice initially (at first_at)

### ISSUE THREAD

**Issue by jmettraux** [jmettraux/rufus-scheduler#231]
As seen in http://stackoverflow.com/questions/41754840/why-is-rufus-scheduling-the-first-job-twice

```ruby
require 'rufus-scheduler'

s = Rufus::Scheduler.new
$i = 0
s.every '5s', :first_at => Time.now + 1 do
  p [ :hello, $i, Time.now.strftime('%H:%M:%S') ]
  $i += 1
end
s.join
```

**Comment by adeeb1** [comment]
Hi there,

Will the gem be updated with this fix soon? Thanks for being a great maintainer!

**Comment by jmettraux** [comment]
Hello @adeeb1 

It's released then: https://rubygems.org/gems/rufus-scheduler/versions/3.3.3

Thanks for your help!
