### ISSUE TITLE
What would you recommend to keep the Rufus instance running when Rails app is restarted?

### ISSUE THREAD

**Issue by sofiabravo103** [jmettraux/rufus-scheduler#234]
I have a scheduler instance is running perfectly in my production environment, but when a capistrano deploy happens it restarts the Rails app and the scheduler stops scheduling. A capistrano deploy might be just a simple hotfix, so I would like to be able to keep the scheduler instance alive somehow.

I know that you say specifically that this is a non-feature in the README (it's still a really awesome gem!), I just wanted to know if there is a way to keep it in a separate ruby process that will not be stopped even if the Rails app is restarted and somehow still be able to access it to call the shutdown method if needed.

**Comment by jmettraux** [comment]
Hello Sofia,

> it restarts the Rails app and the scheduler stops scheduling

If I understand correctly, you're starting the scheduler manually?

**Comment by jmettraux** [comment]
If you want to manage multiple processes, you could look at http://ddollar.github.io/foreman/ I think that that's what Heroku uses (or something similar).

I tend to use http://smarden.org/runit/ just for my applications (not as the general init system) on my debian servers. I could imagine having a runit service dedicated to 1) the webapp 2) the scheduler for it, and have Capistrano push and restart the two services...

On the other hand, I have a few web applications on JRuby (Puma, not in cluster mode) and the scheduler lives in them and is stopped / started with the whole of the webapp.

**Comment by jmettraux** [comment]
Closing the issue but not the conversation.

**Comment by sofiabravo103** [comment]
The scheduler starts manually, like you suggest in the README:
 ```

# config/initializers/scheduler.rb
require 'rufus-scheduler'
Rufus::Scheduler.singleton

```
But the scheduling happens from a controller:
```

 def create
    @harvest_plan = HarvestPlan.new(resource_params)
    @harvest_plan.start_date = Time.parse(resource_params[:start_date])
    if @harvest_plan.save
      ApplicationController.new.insert_in_messages_list(session, :success, 'Harvest plan created')
      schedule_harvest
      redirect_to farms_path
    end
  end
  private

  def schedule_harvest
    if @harvest_plan.repetitions != nil
      Rufus::Scheduler.singleton.every "#{@harvest_plan.hours_between}h",
        :times => @harvest_plan.repetitions, :first_at => @harvest_plan.start_date do
        CreateHarvestFromPlanJob.perform_later(@harvest_plan)
      end
    else
      Rufus::Scheduler.singleton.every "#{@harvest_plan.hours_between}h",
        :first_at => @harvest_plan.start_date do
        CreateHarvestFromPlanJob.perform_later(@harvest_plan)
      end
    end
  end 

```

**Comment by jmettraux** [comment]
I would take a different approach, one with a single schedule (warning some parts are pseudo-code, I haven't used Rails or ActiveRecord in ages):

```ruby
# config/initializers/scheduler.rb

require 'rufus-scheduler'

Rufus::Scheduler.singleton.cron('* * * * *') do
  # every minute

  HarvestPlan.trigger_if_necessary
end
```

```ruby
# app/models/harvest_plan.rb

class HarvestPlan < ApplicationRecord

  def self.trigger_if_necessary

    now = Time.now

    HarvestPlan.where(start_date < now && repetitions > 0) do |plan|
      # warning pseudo active record code !

      elapsed = now - plan.last_time / 3600
      next if elapsed < @harveset_plan.hours_between
        # that elapsed check could even be done in the `where` above

      # clear to trigger

      plan.trigger
    end
  end

  def trigger

    self.repetitions -= 1
    self.last_time = Time.now
    self.save

    CreateHarvestFromPlanJob.perform_later(self)
      # that's ugly, when do not want to perform_later, we want to perform now!
  end
end
```

```ruby
# in the controller...

def create

   @harvest_plan = HarvestPlan.new(resource_params)
   @harvest_plan.start_date = Time.parse(resource_params[:start_date])

   return unless @harvest_plan.save

   ApplicationController.new.insert_in_messages_list(
     session, :success, 'Harvest plan created')

   redirect_to farms_path
end
```


You could even avoid using rufus-scheduler:

```ruby
# config/initializers/scheduler.rb

Thread.new do
  loop do
    begin
      sleep 59
      HarvestPlan.trigger_if_necessary
    rescue => err
      Rails.logger.warn "#{err.object_id} - problem with HarvestPlan triggering... " + err.inspect
      err.backtrace.each do |line|
        Rails.logger.warn "#{err.object_id} - #{line}"
      end
    end
  end
end
```

Best regards.

**Comment by sofiabravo103** [comment]
Thanks a lot for taking the time to write a suggestion! I had a similar approach before starting to use rufus, but it had a lot of problems. I don't think this will work for me, but I'll keep thinking about it

But about my original question...  So there is no way to keep the scheduler instance alive somehow?

**Comment by jmettraux** [comment]
> So there is no way to keep the scheduler instance alive somehow?

There are plenty of ways, some hinted in https://github.com/jmettraux/rufus-scheduler/issues/234#issuecomment-275970444 

But problems or maintenance will happen, your whole server will have to restart and all your schedules will be lost. And at some point too you will want to upgrade the scheduler instance itself.

I think your approach, keeping the scheduler instance alive, is too brittle.

> I had a similar approach before starting to use rufus, but it had a lot of problems. I don't think this will work for me, but I'll keep thinking about it

May I suggest you try that approach another time?  It happens to me a lot of times: I write something, learn from it, then rewrite it, stronger with experience.

**Comment by sofiabravo103** [comment]
I see what you mean. I did not think of the maintenance nightmare it would be.

The thing with the approach you suggested is that having a cron job running all the time (even if it's just a one liner code) and processes sleeping for an hour is just too much for my AWS instance. I think I might lean into something like an initializer that "re-schedules" everything after creating the new rufus-instance, using the harvest plan and delayed job database info. What do you think?

**Comment by jmettraux** [comment]
> the approach you suggested is that having a cron job running all the time

You have to understand that rufus-scheduler scheduling thread is waking up 3 times per second to check its schedules.

I think a (thread + loop + sleep 30 minutes) might be more economical.

Are you afraid of having too many queries on your DB? Or afraid of having too much CPU activity?

**Comment by sofiabravo103** [comment]
I'm afraid of having too much CPU activity and using too much RAM (the server was having out of memory errors when I wrote a solution similar to your suggestion)... Maybe I was writing a bad implementation?

**Comment by jmettraux** [comment]
> Maybe I was writing a bad implementation?

That's probable.

**Comment by sofiabravo103** [comment]
Thanks, I will consider rewriting that approach.
