### ISSUE TITLE
Running Rufus + Rakefile on Heroku

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [jmettraux/rufus-scheduler#236]
@jmettraux 

----

### **How can I run the rufus scheduler with a `Rakefile` on Heroku?**

I can run daily cron tasks for free, but hourly it costs $3/mo! Now I want to use the rufus scheduler gem.

----

> * My GitHub project: https://github.com/buntobot/bunto-issue-bot
> * My Heroku project: https://bunto-issue-bot.herokuapp.com/

----

My `task_scheduler.rb` file:
```ruby
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new

scheduler.every '4h' do
  # do Rake tasks here
end
```

My Rakefile:
```rake
require_relative 'bot'

task :travisci do
  print "It works!"
end

task :process_issues do
  Bunto::Bot.new.start(process: :issues)
end

task :process_prs do
  Bunto::Bot.new.start(process: :prs)
end
```

*Cheers,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by jmettraux** [comment]
Hello Suriyaa,

with a bit of googling you'll find examples on how to run a Heroku worker containing a Clockwork scheduler (not rufus-scheduler but close enough). For example: https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes

Have fun! Best regards.
