### ISSUE TITLE
Documented advanced locking interface example doesn't work

### ISSUE THREAD

**Issue by djrodgerspryor** [jmettraux/rufus-scheduler#239]
The advanced locking example with zookeeper doesn't ever actually call the `lock` method that it overrides: it just calls `@scheduler_lock.lock` directly.

The culprit seems to be this commit here https://github.com/jmettraux/rufus-scheduler/commit/68ffbc3dc2b915747e4ab338390846910b1ecbd6

The new scheduler_lock argument isn't actually a substitute for the subclassing interface from the example in the docs because:
 1) A lock object won't be able to call methods on the scheduler instance (eg.  `shutdown` in the `confirm_lock` method of the zookeeper instance)
 2) There is no `confirm_lock` call for a passed-in scheduler_lock; you could override `confirm_lock` *and* pass in a custom lock object, but that's a pretty convoluted interface.

Proposed fix here: https://github.com/jmettraux/rufus-scheduler/pull/238

**Comment by jmettraux** [comment]
Merged. Thanks a lot!
