### ISSUE TITLE
scheduler call a method automatically after all jobs finished

### ISSUE THREAD

**Issue by lovingyu** [jmettraux/rufus-scheduler#241]
hi ,
   quick question for u.
   after all my jobs finished, i want  scheduler can call a method automatically, is there a method?

   thank you

**Comment by jmettraux** [comment]
Hello,

this could do it:
```ruby
require 'rufus-scheduler'

s = Rufus::Scheduler.new

over = false
s.every '1s' do
  if over == false && s.jobs.size <= 1
    puts "over!"
    over = true
  end
end

s.in '5s' do
  puts "and 5!"
end

s.join
```
It's not immediate. You could monkey patch the engine (or I could provide you a callback)...

Beware the corner cases.

Closing the issue, but not the conversation.

**Comment by lovingyu** [comment]
hi , it works fine . enough for me。
thanks
