### ISSUE TITLE
How to schedule task with dynamic time though rufus-scheduler

### ISSUE THREAD

**Issue by rageshpillai** [jmettraux/rufus-scheduler#250]
My main problem is to set dynamic scheduler through rufus-scheduler, let suppose i have a text fields on which we put minutes, base on that minutes re-schedule rufus-scheduler.

**Comment by jmettraux** [comment]
Answered at https://groups.google.com/forum/#!topic/rufus-ruby/aOVCwXJCUT4

See gist at https://gist.github.com/jmettraux/230aa2e06507a457455a63ad04487481

Closing the issue but not the conversation.

**Comment by rageshpillai** [comment]
scheduler.interval (SchedulerConfig.find_by_job_name "kk").duration, :overlap => false, :first => :now, :tags => [ 'cont.ct' ] do
....
end
when updating the interval time scheduler is not taking the updated value.
i just want to change the interval time of the particular job

**Comment by jmettraux** [comment]
You have first to unschedule the job, else you will end up with two jobs.

Best regards.

**Comment by jmettraux** [comment]
@rageshpillai this might also interest you: https://github.com/jmettraux/rufus-scheduler#every-jobs-and-changing-the-next_time-in-flight

Instead of unscheduling and then rescheduling the job, you can simply follow the example and change the `next_time` on the fly.

**Comment by rageshpillai** [comment]
thank u john

**Comment by jmettraux** [comment]
You are welcome.

**Comment by rageshpillai** [comment]
scheduler = Rufus::Scheduler.new
scheduler.every '5s' do |job|
 p "job time",job.next_time
 job.next_time=Time.now+30
 p "fd",job.next_time
 end
=> "every_1498036590.9886_70118179576740"

 "job time"
#<EtOrbi::EoTime:0x007f8b525793f8 @seconds=1498036600.9887328, @zone=#<TZInfo::TimezoneProxy: Etc/UTC>, @time=nil>
"fd"
2017-06-21 14:47:06 +0530

pls check this code
its not updating the interval.
pls help me resolve

**Comment by jmettraux** [comment]
Hello,

here is something that works for me:
```ruby
require 'rufus-scheduler'

class Rufus::Scheduler::EveryJob
  #
  # allow setting the frequency directly
  #
  attr_writer :frequency
end

scheduler = Rufus::Scheduler.new
scheduler.every '2s' do |job|
  p [ :in, Time.now ]
  job.frequency = rand(4) + 1
  job.next_time = Time.now + job.frequency
  p [ :new_frequency, job.frequency ]
end

scheduler.join
```

I hope it helps. Best regards.

**Comment by rageshpillai** [comment]
i added the same code in the rails console its showing
ArgumentError: comparison of Time with EtOrbi::EoTime failed

**Comment by jmettraux** [comment]
@rageshpillai I need the complete error stack trace.

**Comment by rageshpillai** [comment]
is it possible to update the job.original value?

**Comment by jmettraux** [comment]
@rageshpillai wrote:
> y we need to add frequency in it?

What do you mean?

> is it possible to update the job.original value?

Yes, it's Ruby, you can override it.

**Comment by jmettraux** [comment]
Please try with:
```ruby
require 'rufus-scheduler'

class Rufus::Scheduler::EveryJob
  #
  # allow setting the frequency directly
  #
  attr_writer :frequency
end

scheduler = Rufus::Scheduler.new
scheduler.every '2s' do |job|
  p [ :in, Time.now ]
  job.frequency = rand(4) + 1
  job.next_time = ::EtOrbi::EoTime.now + job.frequency
  p [ :new_frequency, job.frequency ]
end

scheduler.join
```

**Comment by rageshpillai** [comment]
y we need to change the frequency is it req or not?

**Comment by jmettraux** [comment]
> y we need to change the frequency is it req or not?

The frequency is the "interval" you were asking for above.

If you don't change the frequency, the scheduling will occur always at the original interval.

**Comment by rageshpillai** [comment]
scheduler.every '2s' do |job|
  p [ :in, Time.now ]
  
  job.next_time = ::EtOrbi::EoTime.now +60
  p [ :new_frequency, job.next_time ]
end
this one is working for me. with out updating the frequency

**Comment by jmettraux** [comment]
Ah OK, then you're good to go.

Well done!

**Comment by rageshpillai** [comment]
thank u :)

**Comment by rageshpillai** [comment]
scheduler.join is required?

**Comment by jmettraux** [comment]
Hello,

`scheduler.join` tells the current Ruby thread to join the scheduler instance thread. It is useful for small scripts running rufus-scheduler. If you run a rufus-scheduler instance in a web application (Ruby on Rails for example), `scheduler.join` is not necessary (it should even be avoided). It is not necessary because the web server takes care of not exiting its own process unless told otherwise.

Best regards.

See also https://github.com/jmettraux/rufus-scheduler#schedulerjoin

**Comment by rageshpillai** [comment]
is there any way "interval" jobs and changing the next_time in-flight?

**Comment by jmettraux** [comment]
Hello,

> is there any way "interval" jobs and changing the next_time in-flight?

Yes, in the exact same way you did it above with an `EveryJob`.

Best regards.

**Comment by rageshpillai** [comment]
which class i need to override?
"next_time" option  should work as well with cron jobs, not so with interval jobs whose next_time is computed after their block ends its current run.

**Comment by jmettraux** [comment]
> "next_time" option should work as well with cron jobs, not so with interval jobs whose next_time is computed after their block ends its current run.

You are right.

> which class i need to override?

`IntervalJob`

Best regards.

**Comment by jmettraux** [comment]
Or you could simply set the `@interval` and be done.

**Comment by rageshpillai** [comment]
k

**Comment by jmettraux** [comment]
@rageshpillai wrote:
> k

Sorry, what do you mean by that?

**Comment by rageshpillai** [comment]
does overlap:false option work with every jobs

**Comment by jmettraux** [comment]
@rageshpillai I am sorry, I am too busy to take the time to read the documentation for you. Please read the documentation by yourself. If it's not in the documentation, just simply try. If there is anything wrong, please open a detailed issue.

**Comment by rageshpillai** [comment]
In our apps we have 10 background jobs, all are interval jobs
 ```
class Rufus::Scheduler::IntervalJob
  attr_writer :interval
 end

```
am using this class to overidde the interval timing
``
time_delay=(SchedulerConfig.find_by_job_name "job_name").duration
   job.interval=(time_delay.include?("m")) ? (time_delay.scan(/\d+/).first.to_i*60) : (time_delay.include?("h")) ? (time_delay.scan(/\d+/).first.to_i*60*60) : (time_delay.scan(/\d+/).first.to_i*60*60*24)
   next_job_time = Time.now + job.interval
  Rails.logger.info "[UANOCJ] Next job_time=#{next_job_time} and frequency=#{job.interval}s "

all the jobs are working as expected .but after 3 days after the deployment some of the jobs are failing. am not able to under stand what is the exact issue in this.

**Comment by jmettraux** [comment]
@rageshpillai This issue is closed. Feel free to open a new, DETAILED, issue if you encounter a new problem. Thanks for your understanding.
