### ISSUE TITLE
Running cron job in Multiple Timezones

### ISSUE THREAD

**Issue by anushamummina** [jmettraux/rufus-scheduler#251]
I am trying to run a scheduler cron in multiple Timezones and below is my code

```ruby
TZInfo::Timezone.all_country_zone_identifiers.each do |zone|
  job_id = scheduler.cron("00 06 * * * #{zone}") do
   #do the job
   puts "#{Time.now} - Job Done successfully."
  end
end
```
which is leading me to continuous loop which is leading to memory exhaustion. Don't know what exactly is happening. Could you please help me on this.

Thank you in Advance.

**Comment by jmettraux** [comment]
Hello,

this is my code:
```ruby
require 'rufus-scheduler'

puts "zone count:       #{TZInfo::Timezone.all_country_zone_identifiers.size}"
puts "ruby version:     #{RUBY_VERSION}"
puts "ruby platform:    #{RUBY_PLATFORM}"
puts "system:           #{`uname -a`}"
puts "rufus-scheduler:  #{Rufus::Scheduler::VERSION}"

scheduler = Rufus::Scheduler.new 

t0 = Time.now 

TZInfo::Timezone.all_country_zone_identifiers.each do |zone| 
  scheduler.cron("18 14 * * * #{zone}") do 
    p [ Time.now, zone ] 
  end 
end 
puts "\nscheduling done, took #{Time.now - t0}s"

scheduler.join 
```
It outputs:
```
zone count:       416
ruby version:     2.3.3
ruby platform:    x86_64-darwin14
system:           Darwin satsuma.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64 x86_64
rufus-scheduler:  3.4.2

scheduling done, took 1.794799s
```
It schedules as expected and does not seem to consume too much memory:
<img width="713" alt="screen shot 2017-06-22 at 15 22 19" src="https://user-images.githubusercontent.com/3624/27419973-ac093382-575e-11e7-9d5f-37703d6a155f.png">

Now if you could give more details about your usage, I could perhaps help you.

Best regards.

**Comment by anushamummina** [comment]
I am running this scheduler in rails 5. When I am running this in my local development environment it is running for the Timezones(Asia/Kalkata and Asia/Colombio) and is not taking time. But when I am running the same in AWS server(Puma+nginx) in development environment server is getting hanged up and  getting below error in nginx:
`2017/06/22 06:16:40 [error] 29688#0: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 182$`

Until I removed the code and restart the nginx server is not running.

Please help me.

**Comment by jmettraux** [comment]
@anushamummina wrote:
> which is leading me to continuous loop
> which is leading to memory exhaustion

How did you come to this conclusion?

What Ruby version are you using on your server? What rufus-scheduler version? What tzinfo version?

> But when I am running the same in AWS server(Puma+nginx) in development environment server is getting hanged up 

Does it immediately get hanged up?

**Comment by anushamummina** [comment]
Yes when scheduler is started, server is getting hanged up and nginx is not running.

Ruby Version: 2.3.1
Rufus-scheduler Version: 3.2.2
tzinfo Version: 1.2.2

**Comment by jmettraux** [comment]
@anushamummina wrote:
> which is leading me to continuous loop
> which is leading to memory exhaustion

How did you come to this conclusion?

> Yes when scheduler is started, server is getting hanged up and nginx is not running.

Anything appearing in the logs of your application on the server?

> Rufus-scheduler Version: 3.2.2

Have you tried with the last version of rufus-scheduler?

**Comment by anushamummina** [comment]
> How did you come to this conclusion?

As when scheduler is starting, nginx is getting stopped and giving timeout error. For Memory exhaustion, I have 2GB RAM in AWS Server and when I have checked it is showing full. Now I increased RAM Size still nginx is giving timeout error.

> Anything appearing in the logs of your application on the server?

Yes, When I print running job from scheduler I  can see the scheduled jobs(each country timezone one scheduler is getting scheduled)

> Have you tried with the last version of rufus-scheduler?

No, Do you want me to check with latest varsion?

**Comment by jmettraux** [comment]
> As when scheduler is starting, nginx is getting stopped and giving timeout error. For Memory exhaustion, I have 2GB RAM in AWS Server and when I have checked it is showing full. Now I increased RAM Size still nginx is giving timeout error.

I don't understand why you are talking about a continuous loop.

Does the scheduling happens at all? I mean, does at least one schedule trigger?

Anything else appearing in the logs? No Ruby errors?

Have you tried with scheduling in a single timezone? Does that lead to a memory exhaustion?

> No, Do you want me to check with latest varsion?

Not yet. Before that, please answer that question: what code gets actually scheduled? Is that all:
```ruby
   #do the job
   puts "#{Time.now} - Job Done successfully."
```
?

**Comment by jmettraux** [comment]
What happens with this code:
```ruby
TZInfo::Timezone.all_country_zone_identifiers.each do |zone| 
   #puts "TimeZone is: #{zone}"
   #system("rake yoapp:currency_converter")
   #LocalCurrency::CurrencyConverter.new.convert_local_currency_to_dollars
   puts "#{Time.now} - currency exchange rates were updated successfully."
end
```
? When running on your server, does the "hang up" still happen?

**Comment by anushamummina** [comment]
Let me try once. Have you removed the scheduler cron code?

**Comment by jmettraux** [comment]
> Have you removed the scheduler cron code?

I have commented out your CurrencyConverter invocations.

**Comment by anushamummina** [comment]
I am getting this error in puma logs:

```
[28664] * Starting control server on unix:///tmp/puma-status-1498119286655-28664
[28664] ! Terminating timed out worker: 28703
[28664] ! Terminating timed out worker: 28707
[28664] ! Terminating timed out worker: 28923
[28664] ! Terminating timed out worker: 28925
[28664] ! Terminating timed out worker: 28957
[28664] ! Terminating timed out worker: 28959


```
Code:

```
TZInfo::Timezone.all_country_zone_identifiers.each do |zone|
   job_id = scheduler.cron("18 08 * * * #{zone}") do
  #puts "Running Jobs:............ #{scheduler.running_jobs.inspect}"
  #scheduler.cron("5 0 * * *") do
  #puts "TimeZone is: #{zone}"
  #system("rake yoapp:currency_converter")
  #schedule = LocalCurrency::CurrencyConverter.new
   #schedule.convert_local_currency_to_dollars
   puts "#{Time.now} - currency exchange rates were updated successfully."
  end
 end

```

**Comment by jmettraux** [comment]
Does the "hang up" still happen? It's not obvious from your feedback.

**Comment by jmettraux** [comment]
> I am getting this error in puma logs:

It's not an error at all, it's simply a termination notice for timed out workers.

**Comment by anushamummina** [comment]
Yes, server is not running now.
![error](https://user-images.githubusercontent.com/17082744/27424281-25f0eddc-5752-11e7-88cb-d0cd3ac99e94.png)
when I reverted the code(removing timezone loop) server is running and I can see my login page.

**Comment by jmettraux** [comment]
Your screenshot is saying error 500. May I see the Error 500 as seen from the Rails log?

Thanks in advance.

**Comment by anushamummina** [comment]
When I removed my currncyconverter code it is running fine. When I added the code and run I am getting 500 error. But I can't see any error from my rails logs.
 
In my code actually I am connecting to 3rd party API to store data. is it the problem?

**Comment by anushamummina** [comment]
I am using retries in my code. Suppose if it failed for one time means I am retrying the same job for 3 times. 
and the job is failing 3 times. so data is not returning to scheduler and 'puts "#{Time.now} - currency exchange rates were updated successfully.' is not priniting. 

Is it actually causing problem?

**Comment by jmettraux** [comment]
> When I removed my currncyconverter code it is running fine.
>
> In my code actually I am connecting to 3rd party API to store data. is it the problem?

Yes, for me it indicates that rufus-scheduler is not the problem. Closing this issue.

> I am using retries in my code. Suppose if it failed for one time means I am retrying the same job for 3 times.
> and the job is failing 3 times. so data is not returning to scheduler and 'puts "#{Time.now} - currency > exchange rates were updated successfully.' is not priniting.
>
> Is it actually causing problem?

I don't have the code under my eyes and I haven't tried it, but your analysis sounds OK.

Good luck with that! Have a nice day.

**Comment by anushamummina** [comment]
Thank you so much John for helping me out.
