### ISSUE TITLE
sidekiq grabs the jobs

### ISSUE THREAD

**Issue by TAiS46** [jmettraux/rufus-scheduler#257]
Hi there,

our problem is that rufus scheduler gets executed multiple times.
we are starting rails and two sidekiq with foreman.

I am logging the execution with `p [ 'performing...', scheduler.hash, $$ ]`
In the log I see now
```
14:34:15 matching_sidekiq.1 | ["performing...", -1213517737772130212, 53240]
14:34:15 default_sidekiq.1  | ["performing...", -2524800071394972579, 53241]
```

How can I avoid that sidekiq executes the rufus jobs?

Then I would like to have a lock file with
`scheduler = Rufus::Scheduler.singleton(:lockfile => ".rufus-scheduler.lock")`

But then I am getting this
```
14:48:52 matching_sidekiq.1 | "started rufus scheduler"
14:48:52 default_sidekiq.1  | "started rufus scheduler"
14:48:52 default_sidekiq.1  | cannot schedule, scheduler is down or shutting down
```

#### Edit
I fixed the lock problem with `unless scheduler.down?`

**Comment by jmettraux** [comment]
> I fixed the lock problem with unless scheduler.down?

Hello, may I then close this issue?

**Comment by TAiS46** [comment]
First question is not answered.
Sidekiq takes the jobs when sidekiq got executed before rails server

**Comment by jmettraux** [comment]
> First question is not answered.

OK, so your first question is:

> How can I avoid that sidekiq executes the rufus jobs?

What do you mean by that? Sidekiq has nothing to do with rufus-scheduler, rufus-scheduler executes its scheduled jobs by itself.

> Sidekiq takes the jobs when sidekiq got executed before rails server

What do you mean by that? What has rufus-scheduler to do with that?

Considering:
```
14:48:52 matching_sidekiq.1 | "started rufus scheduler"
14:48:52 default_sidekiq.1  | "started rufus scheduler"
14:48:52 default_sidekiq.1  | cannot schedule, scheduler is down or shutting down
```
Does that imply that you start (create an instance of rufus-scheduler) in your Sidekiq worker???

**Comment by jmettraux** [comment]
Thanks.
