### ISSUE TITLE
Scheduling on tuesday every other week

### ISSUE THREAD

**Issue by manveru** [jmettraux/rufus-scheduler#259]
I'm trying to figure out a way to specify a schedule that occurs every two weeks on Tuesday. So far I've only come up with `0 0 * * tue#2,tue#4`, which is not correct as a month may have between 4-5 Tuesdays.

Is there some way to solve this issue using `Rufus::Scheduler::CronLine` or should I implement a final check in my code and simply call it every Tuesday like `Date.today.cweek % 2 == 0`?

**Comment by jmettraux** [comment]
Hello,

I did my own google search and every one seems to be implementing her/his own version of the "final check".

https://serverfault.com/questions/633264/cronjob-run-every-two-weeks-on-saturday-starting-on-this-saturday
https://stackoverflow.com/questions/350047/how-to-instruct-cron-to-execute-a-job-every-second-week

I'd say go with your final check.

Maybe I should allow for some kind of guard when setting up `Rufus::Scheduler::CronLine` (though future versions will use https://github.com/floraison/fugit)

Best regards and thanks for Ramaze and friends.

**Comment by manveru** [comment]
Thanks for the answer, I went ahead with the final check, it's a one-liner anyway but splits the logic in two places which I'm not a big fan of. Either way I think it'd be a pretty useful feature but it's understandable that you wouldn't implement something that's not supported by anything else (and would make calculations even more difficult).

**Comment by jmettraux** [comment]
Should it look like `0 0 * * tue/2`? But then, odd versus even Tuesdays.

**Comment by jmettraux** [comment]
Moved issue to `fugit` where the parsing for future versions of rufus-scheduler is implemented.

Thanks again.

**Comment by jmettraux** [comment]
Another way:

```ruby
scheduler.every('2w', first: next_tuesday_at_midnight()) do
  # ...
end
```
