### ISSUE TITLE
How to do the task immediately after scheduling ?

### ISSUE THREAD

**Issue by kazhian** [jmettraux/rufus-scheduler#260]
For example, I want to do a job every minutes. But when I use ''* * * * *'', the job is done only after a minute (and so on). But I want it to be at 0th minute too.

**Comment by jmettraux** [comment]
Hello,

you can do

```ruby
s.cron '* * * * *', first: :now do  
  # ...                                      
end  
```

See https://github.com/jmettraux/rufus-scheduler#first_at-first_in-first-first_time

Best regards.
