### ISSUE TITLE
Dependency on tzinfo

### ISSUE THREAD

**Issue by gagan93jtg** [jmettraux/rufus-scheduler#262]
Hey @jmettraux , here is some issue I am facing -
I am using rescue-scheduler v4.0.0  
I am using rufus-scheduler v3.0.0  
This [gem page](https://rubygems.org/gems/rufus-scheduler/versions/3.0.0) specifies that with rufus-scheduler v3.0.0, you can use tzinfo >=0  
 But, going through the source code of rufus-scheduler for tag 3.0.0, I see that you are using classes present only in tzinfo v1.x.x and not in tzinfo 0.x.x  
The class which bothers me is `TZInfo::TransitionDataTimezoneInfo` 
Can you please provide some clarification? Correct me if I am wrong.

**Comment by jmettraux** [comment]
Hello,

you're probably using Bundler, so you can easily ensure that you have tzinfo 1.x.x installed and you will thus have no problems.

I hope this will help.

Best regards.

P.S. it's resque-scheduler, not rescue-scheduler.
