### ISSUE TITLE
SignalException - SIGTERM on Heroku 

### ISSUE THREAD

**Issue by jeffblake** [jmettraux/rufus-scheduler#263]
Whenever my server restarts - during a deploy, and typically once per day automatically, I get a `SIGTERM` exception on `scheduler.join`

Anything we can do about this?

**Comment by jmettraux** [comment]
Hello,

you should not need to do `scheduler.join`. Remove that line. It is telling the Ruby main thread to join the rufus-scheduler thread, it is only used in example programs. It is not needed at all in "servers".

Closing the issue but not the conversation.

**Comment by jeffblake** [comment]
If I remove `scheduler.join`, the process cannot start and crashes - both locally and on Heroku.

Procfile
```
clock: bundle exec rake scheduler
```

```
14:14:23 clock.1   | booting scheduler...
14:14:24 clock.1   | exited with code 0
14:14:24 system    | sending SIGTERM to all processes
```

scheduler.rake
```
require 'rufus-scheduler'

task scheduler: :environment do

  $stdout.puts "booting scheduler..."

  scheduler = Rufus::Scheduler.new
  # tasks ommitted..
end
```

**Comment by jmettraux** [comment]
Hello,

https://github.com/jmettraux/rufus-scheduler#getting-help

> If I remove scheduler.join, the process cannot start and crashes - both locally and on Heroku.

How does it crashes? What error message locally? What error message on Heroku?

Warning: I am no Heroku specialist.

Thanks in advance.

**Comment by jmettraux** [comment]
Questions:

> Whenever my server restarts - during a deploy, and typically once per day automatically, I get a SIGTERM exception on scheduler.join

Does that prevent the web part from executing correctly? Does that prevent the scheduling part from executing correctly? In other words, are those SIGTERM exceptions merely annoyances?

Also:

Could you please include the complete `scheduler.rake`, including its `scheduler.join`.

Thanks in advance.

**Comment by jeffblake** [comment]
Well I don't think its crashing, I think that without `scheduler.join`, the rake task finishes and exits immediately as there's nothing to keep it running.

Maybe rufus scheduler just needs to trap `SIGTERM`'s and handle them gracefully? Everything works fine - merely annoyances.

full file

```
require 'rufus-scheduler'

task scheduler: :environment do

  $stdout.puts "booting scheduler..."

  scheduler = Rufus::Scheduler.new

  current_time = Time.current
  current_minute = current_time - (current_time.to_i % 60).seconds
  current_minute_rounded = Time.at(current_minute.to_i) + 1.minute
  # Run job at the top of the minute, every minute
  # If an item goes onsale, we want the cache to be reflected immediately
  scheduler.every '1m', first_at: current_minute_rounded, overlap: false do |job, time|
    job_minute = Time.at(time.to_i)
    stock_items_went_on_sale = StockItem.where('on_sale_at = ? or end_sale_at = ?', job_minute, job_minute)
    event_promoter_ids = []
    stock_items_went_on_sale.find_each do |stock_item|
      stock_item.touch
      event_promoter_ids += stock_item.variant.event_promoter_ids
    end
    event_promoter_ids = event_promoter_ids.uniq
    if event_promoter_ids.any?
      EventPromoter.where(id: event_promoter_ids).find_each &:touch
    end
  end

  #TODO: permanently fix
  scheduler.every '1m' do
    InventoryUnit.on_hand.where.not(line_item_id: nil, order_id: nil).update_all line_item_id: nil, order_id: nil
  end

  scheduler.every '1m', overlap: false do

    Order.delay.release_expired_order_inventory!

    # hack
    # units sometimes, erratically, get stuck on reserved after an order is expired
    InventoryUnit.reserved.joins(:order).merge( Order.where(state: ['expired', 'abandoned', 'canceled']) ).find_each do |unit|
      unit.release!
    end

  end

  scheduler.every '5m', overlap: false do

    Order.delay.send_checkout_emails_for_reserved_orders!

  end

  scheduler.every '15m' do
    PaymentProfile.delay.remove_expired!
    Campaign.delay.deliver_scheduled_campaigns!
    Order.delay.abandon_orders!
  end

  scheduler.every '4h', overlap: false do
    Campaign.delay(queue: :import).check_for_new_guests!
  end

  scheduler.cron '0 18 * * * America/Vancouver' do
    InvoiceTask.delay.run!
    SubscriptionPlan.delay.send_onboarding_emails!
    CompanyUser.delay.daily_digests!
    #RefreshIdentityTokenTask.delay.run!
  end

  scheduler.cron '0 04 * * * America/Vancouver' do

    #TODO: deprecated
    EventTemplate.delay.run_generator

    EventRecurrence.delay.generate_events!

  end

  scheduler.every '30m' do
    Event.delay.send_event_report_emails!
    EventPostEmailTask.delay.run!
  end

  scheduler.every '7d' do
    Email.where.not(body: nil).where('created_at < ?', 6.months.ago).update_all body: nil
  end

  scheduler.join

end
```

**Comment by jeffblake** [comment]
Perhaps this is not a rufus-scheduler concern, see this section: https://devcenter.heroku.com/articles/dynos#graceful-shutdown-with-sigterm

**Comment by jmettraux** [comment]
> Well I don't think its crashing

Then do not write "the process cannot start and crashes". Stick to the facts.

> Perhaps this is not a rufus-scheduler concern, see this section:
> https://devcenter.heroku.com/articles/dynos#graceful-shutdown-with-sigterm

OK. problem solved.

Best regards.
