### ISSUE TITLE
Rufus + Puma + Docker = Job runs twice

### ISSUE THREAD

**Issue by prettyGoo** [jmettraux/rufus-scheduler#264]
I have a Puma based Rails app which runs inside the Docker. I try to create a rufus job which will run every hour a built-in Rails ActiveJob (sidekiq is used for backend). But it ends up with job running twice.

```ruby
require 'rufus-scheduler'

s = Rufus::Scheduler.singleton

s.every '1m', blocking: true do
  puts "started Scheduler #{s.object_id}"
  Rails.logger.info "hello, it's #{Time.now}"
end
```
 _puts_ (as well as my ActiveJob) triggers twice with different object_id. But _logger_ triggers once.

Any idea why this is happening?

**Comment by jmettraux** [comment]
Hello,

> But it ends up with job running twice.

OK, I assume the job gets sent to Sidekiq twice.

> Any idea why this is happening?

You're probably having two Ruby processes scheduling.

Please read the documentation at https://github.com/jmettraux/rufus-scheduler#lockfile--mylockfiletxt there are ways to prevent redundant rufus-scheduler instances from starting explained there.

Best regards.

**Comment by jmettraux** [comment]
> But logger triggers once.

That begs the question: is your logger set to sync true?

**Comment by jmettraux** [comment]
```ruby
require 'rufus-scheduler'

s = Rufus::Scheduler.singleton

s.every '1m', blocking: true do
  puts "started Scheduler #{s.object_id}, Ruby process id: #{Process.pid}}"
  Rails.logger.info "hello, it's #{Time.now}"
end
```
