### ISSUE TITLE
Documentation: :overlap and :mutex option precedence

### ISSUE THREAD

**Issue by vais** [jmettraux/rufus-scheduler#272]
In the README, in the `:overlap => false` section, it says:
```
The :overlap option is considered **after** the :mutex option when the scheduler is reviewing jobs for triggering.
```
Then, in the `:mutex => mutex_instance / mutex_name / array of mutexes` section, it says:
```
The :overlap option is considered **before** the :mutex option when the scheduler is reviewing jobs for triggering.
```
Which one is right? Or am I missing something...

**Comment by jmettraux** [comment]
Closing, hoping the rework makes it clearer.

Thanks a lot!

**Comment by vais** [comment]
Yes indeed, thanks!
