### ISSUE TITLE
Documentation: CronJob methods section, frequency

### ISSUE THREAD

**Issue by vais** [jmettraux/rufus-scheduler#274]
https://github.com/jmettraux/rufus-scheduler#frequency-1

```
pry(main)> Rufus::Scheduler.parse('* * * * *').frequency
NoMethodError: undefined method `frequency' for #<Fugit::Cron:0x00007fbe4b063b80>
```

Maybe this is something that used to work in an older version?

**Comment by jmettraux** [comment]
Thanks for the question.

I updated the documentation and got rid of `CronJob#frequency`.

Closing this, but if you have suggestions, they are welcome.

Thanks again.
