### ISSUE TITLE
Run job every given time but with delay time using every

### ISSUE THREAD

**Issue by mdesantis** [jmettraux/rufus-scheduler#275]
Hello!

I have a job which should run every 4 hours at minute 30. The cron syntax `'30 */4 * * *'` can be used in order to achieve that. But I'm wondering if there is some way to use the `every` syntax? Maybe an `at` argument could be added to `every`, so we could do something like:

```ruby
scheduler.every '4h', at: '30m' do
  # do something every 4 hours at minute 30
end
```

Thanks!

**Comment by jmettraux** [comment]
Side information: `fugit` behind rufus-scheduler has a "natural" module which will get used in rufus-scheduler soon: https://github.com/floraison/fugit#fugitnat

I can imagine something like:
```ruby
scheduler.schedule('every 4 hours at minute 30') do
  # ...
end
```
that would be equivalent to:
```ruby
scheduler.cron('30 */4 * * *') do
  # ...
end
```

**Comment by mdesantis** [comment]
Hi @jmettraux, thanks for suggestions! I also think that cron syntax is better than that dynamic calculation (cron syntax isn't even bad to me), anyway I think that

```ruby
scheduler.schedule('every 4 hours at minute 30') do
  # ...
end
```

will be a great addition. But I must say that I'd still prefer something like `scheduler.every '4h', at: '30m'`, IMHO it doesn't have neither the obfuscated syntax of cron or the too conversational syntax of `'every 4 hours at minute 30'`

**Comment by jmettraux** [comment]
Hello,

I think that `scheduler.every '4h', at: '30m'` is nice, but what's the pattern? What's the bigger picture? `scheduler.every '4M', at: 'first monday 17h30m'`, how can it be generalized? There seems to be a big space behind that door.
