### ISSUE TITLE
 Get second and third next_time

### ISSUE THREAD

**Issue by filipeaugustosantos** [jmettraux/rufus-scheduler#281]
How to get the next events?
For example, I need a list of the next three executions.

**Comment by jmettraux** [comment]
Good morning,

for a start, you could do something along those lines:

```ruby
require 'rufus-scheduler'

scheduler = Rufus::Scheduler.new
scheduler.cron '1 * * * *' do; end
scheduler.every '2m' do; end
scheduler.in '3m' do; end

scheduler.jobs.each do |job|
  p [ job.class, job.original, job.next_time.to_t ]
end
```

Closing the "issue", not the conversation.

Best regards.

**Comment by filipeaugustosantos** [comment]
I got that way


cron = js[0].to_s
		begin			
			t1 = Rufus::Scheduler.parse(cron).next_time.to_s
			t2 = Rufus::Scheduler.parse(cron).next_time(t1).to_s
			t3 = Rufus::Scheduler.parse(cron).next_time(t2).to_s
			result << t1.to_s
			result << t2.to_s
			result << t3.to_s	
		rescue
		end
