### ISSUE TITLE
Handlers and multithreading

### ISSUE THREAD

**Issue by ViTVetal** [jmettraux/rufus-scheduler#283]
Hello!
I want to use rufus-scheduler on the puma production server so my code should be thread-safe. I have similar code (handler)
https://github.com/jmettraux/rufus-scheduler#scheduling-handler-classes

```
class MyHandler
  def initialize(value)
    @count = value
  end

  def call(job)
    @count += 1
  end
end

my_handler = MyHandler.new(0)
scheduler.every '40s',  my_handler,  :first => :now 
```

`count` instance variable will increase each 40 seconds. So is this code thread-safe?

**Comment by jmettraux** [comment]
Hello,

> https://github.com/jmettraux/rufus-scheduler#scheduling-handler-classes
> So is this code thread-safe?

Yes, as long as your scheduler is the only thing calling your instance of MyHandler, this particular code should be thread-safe.

Best regards.
