### ISSUE TITLE
`pop': execution expired (Net::OpenTimeout)

### ISSUE THREAD

**Issue by darlandieterich** [jmettraux/rufus-scheduler#291]
When send mail, this show in prompt -> "`pop': execution expired (Net::OpenTimeout)"

**Comment by jmettraux** [comment]
Hello,

could you please give me the whole error backtrace (it's something that looks like [this](https://gist.github.com/jmettraux/4832bd41b8f5cc79730ff79ab3cd07ee)).

Could you also please show me the code where the problem occurs.

This is probably not related to rufus-scheduler, it seems your code is attempting to open a network connection and times out. But I will try to help you anyway.

Best regards.

**Comment by darlandieterich** [comment]
Hi @jmettraux you were right, this not related to rufus-scheduler.
I was calling method mail with "deliver" inside. I solved using "deliver" out of method calling.
Sorry for the unnecessary issues
Thank you.

**Comment by jmettraux** [comment]
Ah, no worries, you are welcome!
