### ISSUE TITLE
rufus-scheduler causing Puma to stall on start

### ISSUE THREAD

**Issue by codyrickmanvessel** [jmettraux/rufus-scheduler#296]
I am having an issue that seems to have come up in previous releases. On my Dev machine I am testing using rails server -b 0.0.0.0 If I comment out the rufus-scheduler initialization it starts up fine. If I dont, the rufus tasks run fine, but puma stays in a stalled state and the rest of my application does not respond to requests. 

scheduler.rb is in config/initializers

My Gem File
![image](https://user-images.githubusercontent.com/48725039/64186697-45bf4280-ce3d-11e9-8f20-1ee2952597c8.png)

Puma Config
![image](https://user-images.githubusercontent.com/48725039/64186663-38a25380-ce3d-11e9-8e98-ee9d86a3d3a9.png)

Scheduler File
![image](https://user-images.githubusercontent.com/48725039/64186714-4d7ee700-ce3d-11e9-90e5-d8f8010b489c.png)

**Comment by jmettraux** [comment]
Hello,

could you please package a minimal project similar to your setup (preferably as a github repository) that reproduces the problem so that I can clone it, confirm the problem, and help you solve the issue?

Thanks in advance.

**Comment by jmettraux** [comment]
Also,

what do you mean by

> I am having an issue that seems to have come up in previous releases

?

Did it work with older releases of rufus-scheduler?

Thanks in advance.

**Comment by codyrickmanvessel** [comment]
Hey @jmettraux This is my first time using it. While researching the issue I have seen an issue similar to the one I am having pop up in previous versions (3.0.3 and puma 2.9.2 for example). It seems updating Puma to a new version fixed the issue in one of those instances. However, I believe I have the most recent gems for both installed and I am still having the issue.

**Comment by jmettraux** [comment]
> I have seen an issue similar to the one I am having

If you have a link to that, that could help.

Waiting for your minimal project.

**Comment by codyrickmanvessel** [comment]
@jmettraux here is one of the old topics I discovered: https://github.com/puma/puma/issues/607

I am not sure when I will have time to package a test project, but as soon as I too I will let you know!

Thank You!

**Comment by jmettraux** [comment]
@codyrickmanvessel wait, you should remove `scheduler.join` from your "Scheduler file". It tells the main thread to join the scheduler thread. I think that that is the thing stalling your Puma. Please have a try.

This `scheduler.join` is for standalone example. I will ensure the documentation is clearer on that.

**Comment by codyrickmanvessel** [comment]
@jmettraux  Wow, sorry about that! I thought it was part of the standard initialization. Thank you!

**Comment by jmettraux** [comment]
No worries! Glad it works! Have a great day!
