### ISSUE TITLE
How to schedule a job and stop after some time?

### ISSUE THREAD

**Issue by lucas-ribeiro-bv** [jmettraux/rufus-scheduler#317]
Hi!

There's a way to schedule a job to run every 30 seconds for 3 hours? 

Something like shutdown the scheduler after 3 hours.

(Ps. I am currently working on Logstash, using the Rufus/cron sintax)

Thanks!

**Comment by jmettraux** [comment]
Hello,

I don't know much about Logstash use of rufus-scheduler. I will reply as if you were using a normal rufus-scheduler.

> There's a way to schedule a job to run every 30 seconds for 3 hours?

This starts at `t1` and ends at `t1 + 3 hours`
```ruby
t1 = Time.now + 3600 # 1 hour from now
t2 = t1 + 3 * 3600
scheduler.every '30s', first_at: t1, last_at: t2 do
  # do the job...
end
```

See https://github.com/jmettraux/rufus-scheduler#last_at-last_in-last

> Something like shutdown the scheduler after 3 hours.

Maybe you don't want to shutdown the scheduler, maybe it's given to you by Logstash and you want to use it again later on.

I hope this helps. Best regards,

**Comment by lucas-ribeiro-bv** [comment]
It's possible to use something like that using the cron notation? 

Something like */30 * * * * * last_at: t2

**Comment by jmettraux** [comment]
Hello, yes, it is possible.

```ruby
require 'rufus-scheduler'

$stdout.sync = true

scheduler = Rufus::Scheduler.new

la = Time.now + 30
p [ :last_at, la ]

scheduler.cron '*/5 * * * * *', last_at: la do |job|
  puts Time.now
end

sleep 60
```
yielded for me:
```
[:last_at, 2021-01-23 05:55:11 +0900]
2021-01-23 05:54:45 +0900
2021-01-23 05:54:50 +0900
2021-01-23 05:54:55 +0900
2021-01-23 05:55:00 +0900
2021-01-23 05:55:05 +0900
2021-01-23 05:55:10 +0900
```

Best regards.
