### ISSUE TITLE
Please allow arbitrary content-type headers

### ISSUE THREAD

**Issue by MikeKemmerer** [jmettraux/rufus-scheduler#319]
By forcing either appliaction/json or text/plain with the body_format parameter, it prevents the use of valid content-types (in my use case x-www-form-urlencoded). Please do not overwrite the content-type header unless, perhaps, it is not already set.

**Comment by jmettraux** [comment]
Hello,

rufus-scheduler has no body_format, it doesn't set any mime types.

Please do not post issue report when there are none.

Best regards.
