### ISSUE TITLE
Ideas and discussion about tracking behavior

### ISSUE THREAD

**Issue by jjb** [jmettraux/rufus-scheduler#322]
While debugging something recently, I came up with two hacky methods to track the behavior of a scheduler. First I'll describe what I did and then discuss some ideas

In both cases I'm using line number to identify a job. The more thorough approach would have been to give each job a [name](https://github.com/jmettraux/rufus-scheduler/issues/309), but I wanted to throw together something quickly for debugging purposes.

I had a problem where some jobs were taking a very long time and others weren't, and a related problem where one job was using up a lot more threads than others.

Let me know how interested you might be in PRs for either of these, and/or if you have ideas for how to implement in Rufus!

### report line number of job along with its duration to my stats tracker

```ruby
# in on_post_trigger
# ...
line = job.handler.inspect.split[1].split(':')[1].delete_suffix('>') rescue 'ERROR'
StatTracker.value("Clock: Job #{line} Execution Time", duration.round(2))
# ...
```

### report line number of which job is using which thread

```ruby
schedule.every '5 seconds' do
  which_jobs = schedule.work_threads(:active).map do |t|
    t.backtrace.first.split.first.split(':')[1]
  end
  puts which_jobs.sort.join(', ')
end
```

### 1. somehow associate job names with threads

If a name is given to a job, it would be great to be able to see which active threads in `schedule.work_threads(:active)` are being used by which job (is this somehow currently possible?).

### 2. An automatic name for each job

I'm using line numbers to identify jobs and it worked great for my purposes, but of course this is brittle because line numbers will change as the code changes. What if we had some other natural automatic name per job? For my purposes, in I think all cases, the first line of the job's lambda, stripped, would work perfectly. I haven't looked into how to access a Rufus job's block but here's a simple demo for methods, lambdas, and blocks:

```ruby
require 'method_source'

class Thing
  def bar
    Hash.new
  end
end
puts Thing.new.method(:bar).source
# "  def bar\n    Hash.new\n  end\n"

l = lambda{
  puts "this is my lambda"
}
puts l.source
# l = lambda{
#   puts "this is my lambda"
# }


def takes_a_block(&block)
  puts block.source
end
takes_a_block do
  puts "this is the block i passed in"
end
# takes_a_block do
#   puts "this is the block i passed in"
# end
```

**Comment by jmettraux** [comment]
`Job#name` https://github.com/jmettraux/rufus-scheduler/blob/64591be6a2c80149839861389a0ed8708e279198/spec/job_spec.rb#L389-L397

**Comment by jmettraux** [comment]
Hello,

I have the impression the hacks are better at the level of your [ruby-clock](https://github.com/jjb/ruby-clock) gem.

Regarding the name, how about

```ruby
class Rufus::Scheduler::Job
  def full_name
    [ name, source_location.map(&:to_s).join(':') ].join(' ')
  end
end
```

which returns something like `"alice /home/jmettraux/w/rufus-scheduler/spec/job_spec.rb:408"` ?

It uses the `#source_location` method I added to `Job`.

Best regards.

**Comment by jjb** [comment]
wow cool! thanks!

do you know if there's a way to access the job from `schedule.work_threads(:active).first`?

**Comment by jmettraux** [comment]
Hello,

yes, you can do

```ruby
scheduler.work_threads(:active).each_with_index do |t, i|
  puts "#{i}. work thread #{t.id} is active for job #{t[:rufus_scheduler_job].source_location}"
end
```
Is that sufficient?

**Comment by jjb** [comment]
this is perfect - this code gives me exactly what i wanted

```ruby
  job_code = schedule.work_threads(:active).map do |t|
    t[:rufus_scheduler_job].handler.source.split("\n")[1].strip
  end
```

**Comment by jmettraux** [comment]
OK, give me one or two days to release with `Job#source_location`, then I will close this issue.

Best regards.

**Comment by jjb** [comment]
Thanks, for now I don't need it for what I'm working on, so no time pressure here. I'll let you know what I come up with.

**Comment by jjb** [comment]
Okay, I've made `Rufus::Scheduler::Job#identifier` https://github.com/jjb/ruby-clock/pull/2

I'm going to implement this at work first to see if I want to update anything, so it will get merged and released in the next few days. Any feedback welcome!

**Comment by jjb** [comment]
just got a confusing error message from this code:

```ruby
  schedule.work_threads(:active).each do |t|
    thread_usage[t[:rufus_scheduler_job].identifier] += 1
  end
```

> undefined method `identifier' for true:TrueClass


it happened exactly once when my clock process started. Now that loop, which runs every 10 seconds, seems to be happy and functional.

Is there some kind of fallback scenario where that value might be `true` instead of the job instance?

**Comment by jmettraux** [comment]
> Is there some kind of fallback scenario where that value might be true instead of the job instance?

Hello,

It's not a fallback, it's a temporary `true` value, to pre-reserve before assignation. IIRC.

https://github.com/jmettraux/rufus-scheduler/blob/master/lib/rufus/scheduler/jobs_core.rb#L311-L312

**Comment by jjb** [comment]
Gotcha, thanks! So it's only when the thread is starting up. so i think i can safely just `next` along when i see that and not risk losing any data

**Comment by jmettraux** [comment]
"losing data" sounds scary.

There is also the case where the thread use by the job just ended and it pops in your loop because when the `.threads(:active)` array was established it serviced a job, but when you consider it, it might have ended. I would do something like

```ruby
  schedule.work_threads(:active).each do |t|
    i = t[:rufus_scheduler_job].identifier rescue nil
    thread_usage[i] += 1 if i
  end
```

**Comment by jmettraux** [comment]
[3.8.0 released](https://rubygems.org/gems/rufus-scheduler/versions/3.8.0)

Thanks!

**Comment by jjb** [comment]
great! and thanks for the extra info about missing jobs
