### ISSUE TITLE
schedule_at("Wed at 2pm")  should always be the next available Wed at 2pm

### ISSUE THREAD

**Issue by richardahasting** [jmettraux/rufus-scheduler#340]
First off, this is the greatest gem since sliced bread. So very helpful in a little task I am working on. Keeps me from having to write my own while loop, essentially. So first off, thank you very much for the tool kit.

I was having an issue of wanting to run things every "Mon, Wed,  Fri at 2pm" I ran into an unexpected behavior...
If a date or a time can be generated in the past, it will.

for example:

```ruby
puts Rufus::Scheduler.parse "Wed at 2pm"
```

generates 

`2023-04-26 14:00:00 -0500`

Also, 

```ruby
puts Time.now
puts Rufus::Scheduler.parse "Apr 25 at 2pm"
```
==>
```
2023-04-27 13:45:28 -0500
2023-04-25 14:00:00 -0500
```

should be in the next year if the current time has passed.

```ruby
scheduler.at "Wed 2pm" do
  puts "this should not run now"
end
```

Runs right away. It should not.

I can workaround this, I am pretty sure, but it was not the behavior I was expecting.
thanks again
Richard

**Comment by jmettraux** [comment]
Thanks a lot for reporting that! I will work on it.

**Comment by jmettraux** [comment]
Hello,

the [Chronic](https://github.com/mojombo/chronic) gem might help:

```ruby
require 'chronic'
require 'rufs-scheduler'

scheduler = Rufus::Scheduler.new

scheduler.at "Wed 2pm" do
  puts "this will not run now"
end
```

Please tell me if it doesn't work for you and I will re-open this issue if necessary.

Kind regards,

John
