### ISSUE TITLE
add tzinfo-data as dependency too

### ISSUE THREAD

**Issue by rubemz** [jmettraux/rufus-scheduler#72]
getting this when running bundle

```
TZInfo Timezone Data has Moved
==============================

The timezone data previously included with TZInfo as Ruby modules has now been
moved to a separate tzinfo-data gem. TZInfo also now supports using the system
zoneinfo files on Linux, Mac OS X and other Unix-like operating systems.

If you want to continue using the Ruby timezone modules, or you are using an
operating system that does not include zoneinfo files (such as
Microsoft Windows), you will need to install tzinfo-data by running:

gem install tzinfo-data

If tzinfo-data is installed then TZInfo will use the Ruby timezone modules.
Otherwise, it will attempt to find the system zoneinfo files. Please refer to
the TZInfo documentation (available from https://rubygems.org/gems/tzinfo) for
further information.
```

**Comment by gagan93jtg** [comment]
Hey @jmettraux , here is some issue I am facing -
I am using rescue-scheduler v4.0.0  
I am using rufus-scheduler v3.0.0  
This [gem page](https://rubygems.org/gems/rufus-scheduler/versions/3.0.1) specifies that with rufus-scheduler v3.0.0, you can use tzinfo >=0  
 But, going through the source code of rufus-scheduler for tag 3.0.0, I see that you are using classes present only in tzinfo v1.x.x and not in tzinfo 0.x.x  
The class which bothers me is `TZInfo::TransitionDataTimezoneInfo` 
Can you please provide some clarification? Correct me if I am wrong.

**Comment by jmettraux** [comment]
Hello @gagan93jtg,

sorry but could you please not post in a closed thread. Your issue has nothing to do with the initial issue.

Please open a new issue. Please not that rescue-scheduler does not exist.

Best regards.
