### ISSUE TITLE
Multiple time zone option for cron

### ISSUE THREAD

**Issue by aditya-mandal** [jmettraux/rufus-scheduler#81]
Hi

I would like to schedule a job at 8:00am, but it is specific for some time zone.

Can we set multiple time zones in cron properties.

I found the option to set the time zone but how i can able to set multiple time zones.
Please suggest

scheduler.cron '0 22 \* \* 1-5 Europe/Paris' do
    # every day of the week when it's 22:00 in Paris
 end

**Comment by anushamummina** [comment]
@jmettraux Hi John, I am trying to run a scheduler cron in multiple Timezones and below is my code
```

TZInfo::Timezone.all_country_zone_identifiers.each do |zone|
  job_id = scheduler.cron("00 06 * * * #{zone}") do
   #do the job
   puts "#{Time.now} - Job Done successfully."
  end
end
```
which is leading me to continuos loop which is leading to memory exhaustion. Don't know what exactly is happening. Could you please help me on this.

Thank you in Advance.

**Comment by jmettraux** [comment]
@anushamummina Please open a NEW issue, do not recycle an issue that has been closed. Thanks in advance.

**Comment by anushamummina** [comment]
Hi John,

I have created new issue
https://github.com/jmettraux/rufus-scheduler/issues/251

could you please have a look and help me.

Thank you

Regards,
Anusha M.
